### ISSUE TITLE
backdropClosesModal + showThumbnails = problem

### ISSUE THREAD

**Issue by AlvMF1** [jossmac/react-images#101]
If we use `backdropClosesModal = true` and `showThumbnails = true` and try to navigate using the thumbnails, it closes the lightbox.

**Comment by jossmac** [comment]
@AlvMF1 thanks for the heads up!

**Comment by benhowell** [comment]
Looks like this has already been fixed in master by @GregoryPotdevin:
https://github.com/jossmac/react-images/commit/543dc8e6682afae5982b2df8fb1a62acacbfdd0c

**Comment by jossmac** [comment]
@benhowell good catch, might be time for a release

**Comment by inakiabt** [comment]
@jossmac I'm anxiously waiting for this release 👍

**Comment by jossmac** [comment]
@AlvMF1 @inakiabt `0.5.2` is available on npm

**Comment by inakiabt** [comment]
Just in time, thanks
