### ISSUE TITLE
Incompatibility with Webpack (version 0.5.2)

### ISSUE THREAD

**Issue by matanlb** [jossmac/react-images#104]
Since the publication of version 0.5.2 the package causes error in the webpack build.

v0.5.2 introduced  the usage of [react-scrolllock](https://github.com/jossmac/react-scrolllock) to which webpack throws the following error:
`SyntaxError: Unexpected token: name (ScrollLock) [./~/react-scrolllock/src/ScrollLock.js:10,0]
`

I think that might be due to the fact that react-scrolllock is using es6 syntax (classes) but is published untraspiled, but I haven't had a chance to test that yet.

**Comment by jossmac** [comment]
@matanlb thanks for the heads up. Please let me know what you find once tested

Happy to just use `createClass()` if necessary. Seems over the top to introduce Babel, et al. for such a small utility

**Comment by pwmckenna** [comment]
Also experiencing this issue. Pinning to 0.5.1 fixed it. Definitely the case that react-images is compiled, but scrolllock is not now that it is in a different repo.

**Comment by jossmac** [comment]
@matanlb @pwmckenna `react-scrolllock@1.0.2` now using exclusively ES5.

Please update node modules and let me know how it goes

**Comment by khakulov** [comment]
@jossmac 
```javascript
{
	componentWillMount() { ... }
}
```

is not ES5!!! It should be
```javascript
{
	componentWillMount: function() { ... }
}
```

**Comment by jossmac** [comment]
@khakulov oh god. It's been so long! haha

**Comment by jossmac** [comment]
@khakulov `v1.0.3` is online with updates, please try again

**Comment by matanlb** [comment]
@jossmac thanks for the fix 👍
Everything seems to work now

**Comment by pwmckenna** [comment]
thanks @jossmac!
