### ISSUE TITLE
Thumbnails are not centralized on Safari and FF

### ISSUE THREAD

**Issue by AlvMF1** [jossmac/react-images#105]
**Steps to reproduce the behavior:**
Open [http://jossmac.github.io/react-images](http://jossmac.github.io/react-images) (with thumbnails example) on Safari 10.0.1 (macOS 10.12.1) or  FireFox 50.0.

**Expected behavior:**
Thumbnails centralized. It works on Chrome 54.0.28.

![screen shot 2016-11-25 at 3 53 26 pm](https://cloud.githubusercontent.com/assets/15204146/20636748/87be5f56-b327-11e6-9cb4-72e01ad76753.png)

**Actual behavior:**
Thumbnails are not centralized.

![screen shot 2016-11-25 at 3 54 16 pm](https://cloud.githubusercontent.com/assets/15204146/20636752/8f6cd264-b327-11e6-9836-9ad46b43895c.png)

**Comment by jossmac** [comment]
@AlvMF1 thanks for the heads up

**Comment by triple1c86** [comment]
erm the bug still there in landscape mode.. not centralised.
![whatsapp image 2017-05-15 at 3 18 00 am](https://cloud.githubusercontent.com/assets/2044519/26036412/a0038d32-3920-11e7-87f0-1a13e32ab21d.jpeg)

**Comment by Viktor6713** [comment]
Still an issue in Safari. This css helps:
`#lightboxBackdrop > div:nth-of-type(2) {
  left: 50%;
  transform: translateX(-50%);
}`

I would add this into `paginatedThumbnails` styles.

**Comment by neptunian** [comment]
this could be why: https://www.w3.org/TR/css-flexbox-1/#abspos-items
at least in safari.  thanks @Viktor6713, i'll use your solution.
