### ISSUE TITLE
Scrolllock don't unlock touch on chrome mobile

### ISSUE THREAD

**Issue by jklemm** [jossmac/react-images#113]
**Steps to reproduce the behavior:**

I have two pages on system, `PageOne` and `PageTwo`.  I use the react-router to route between URLs.

I use Lightbox on the Page Two when user clicks on an image.  So, after open Lightbox, just click on `previous button` of chrome mobile browser and return to PageOne, but the scroll don't work more using touch.

Looking the Lightbox source I found the ScrollLock component that is responsible for "Lock the body" while Lightbox is open.   When unmount ScrollLock component it unlocks the body html tag to scroll normally.

Using the X close icon, everything goes fine, but using the back button of android device while the Lightbox is open, not.

**Expected behavior:**

Scrollbar working using touch after click on back button.

**Actual behavior:**

Scrollbar don't work using touch.

**Comment by jossmac** [comment]
That's interesting, I guess the component doesn't really unmount. Thanks for the report

**Comment by jklemm** [comment]
Hi @jossmac, thanks to your quick response.

Can I unmount manually? Or exist an work-a-round to solve this?

Even I can unmount manually, it's hard to detect `previous button` has been pressed.

Cheers.

**Comment by jossmac** [comment]
I think the problem lies with using [react-addons-css-transition-group](https://www.npmjs.com/package/react-addons-css-transition-group) as the component must be mounted to function, and interaction is governed by the `isOpen` prop.

I might have a look into [react-motion](https://www.npmjs.com/package/react-motion) to allow proper mount/unmount behaviour.

**Comment by creatifyme** [comment]
Any update to this? We're running into the same issue.

**Comment by xgmolinax** [comment]
Having the same issue on chrome browser. Have you guys figured out a workaround?

**Comment by romanlex** [comment]
I can confirm. Chrome browser same issues

**Comment by hughkolias** [comment]
anyone have any luck with this? We're having similar issues on all browsers, even when clicking the "X". 

We're on react-addons-css-transition-group and using redux if those have any impact?

@jossmac

**Comment by SoenkeHu** [comment]
How about a disableScrolllock prop for a temporary workaround?

**Comment by jossmac** [comment]
Closing in favour of #179
