### ISSUE TITLE
 If backdropClosesModal is True, onClickImage is activated and backdropClosesModal is activated

### ISSUE THREAD

**Issue by seohangyu** [jossmac/react-images#114]
If backdropClosesModal is True, onClickImage is activated and backdropClosesModal is activated.

How to solve it

**Comment by jossmac** [comment]
`preventDefault` from the function passed to `onClickImage` e.g.

```jsx
class Seohangyu extends Component {
  handleImageClick(e) {
    e.preventDefault()
  }
  render () {
    <Lightbox
      onClickImage={this.handleImageClick}
    />
  }
}
```

**Comment by seohangyu** [comment]
The way you sent it was not resolved.
 However,  'preventDefault' has been corrected to 'stopPropgation' and solved Your quick answer was a great help. Thank you.

**Comment by jossmac** [comment]
@seohangyu right, yeah makes sense - my mistake. Glad your issue is resolved.
