### ISSUE TITLE
npm build fails

### ISSUE THREAD

**Issue by luojxxx** [jossmac/react-images#117]
**Steps to reproduce the behavior:**
git clone <repo>
npm install
npm run build

**Expected behavior:**
rebuild library with changes

**Actual behavior:**
fails

I've attached the npm debug log if you could provide any tips about how to get it running would be greatly appreciated. Thanks!

[npm-debug.txt](https://github.com/jossmac/react-images/files/691258/npm-debug.txt)

**Comment by jossmac** [comment]
@luojxxx the build script is just for use prior to npm publishing.

If you're trying to run the examples app locally you can use `npm start`.
