### ISSUE TITLE
Adding annotations to images

### ISSUE THREAD

**Issue by varatep** [jossmac/react-images#118]
Is there any way to add the annotorious library [https://github.com/annotorious/annotorious](url), or alternative methods to enable annotating of images while the lightbox is open?

**Comment by jossmac** [comment]
@varatep what if you could just add the alt text to the image object?

A similar problem has come up before (ref #92) and I think it could be solved by passing through any valid DOM attributes to the `<img />` tag when rendering the current image; you would use like this:

```jsx
<Lightbox images={[
  {
    src: 'images/awesome.jpg', // accepted
    alt: 'My awesome image', // accepted
    draggable: false, // accepted
    custom: 'for whatever reason', // ignored
  }
]} />
```

**Comment by jossmac** [comment]
@varatep ping!

**Comment by neptunian** [comment]
could be made possible with #54 ?
