### ISSUE TITLE
Support image rotate

### ISSUE THREAD

**Issue by sosilence** [jossmac/react-images#120]
Actually, in many cases, we need to rotate the image when show them in 'react-images', because some of the maybe 90deg rotate for example, this is not convenient to look just as the following screenshot.
![receipt-q](https://cloud.githubusercontent.com/assets/7006569/22194521/fd51c896-e17d-11e6-998c-2f3a06ae4649.png)

So I think add a button in header width rotate icons will be a useful improvement.

**Comment by benhowell** [comment]
@sosilence 
Take a look at the `customControls` prop. You'll need something like https://github.com/exif-js/exif-js to read the orientation, then rotate accordingly using css transform rotate.

I use the exif library in one of my projects and it's very simple to use.
