### ISSUE TITLE
The props rightArrowTitle and leftArrowTitle are not working

### ISSUE THREAD

**Issue by denissonpaz** [jossmac/react-images#128]
**Steps to reproduce the behavior:** install the version 0.5.2, add any text for the props rightArrowTitle or leftArrowTitle. The title remained the same.

**Expected behavior:** Change the title of the arrows

**Actual behavior:**  The title of the arrows are not changing. If you check the code, its hard coded:

`// ==============================
		// RENDERERS
		// ==============================

	}, {
		key: 'renderArrowPrev',
		value: function renderArrowPrev() {
			if (this.props.currentImage === 0) return null;

			return _react2['default'].createElement(_componentsArrow2['default'], {
				direction: 'left',
				icon: 'arrowLeft',
				onClick: this.gotoPrev,
				title: 'Previous (Left arrow key)',
				type: 'button'
			});
		}
	}, {
		key: 'renderArrowNext',
		value: function renderArrowNext() {
			if (this.props.currentImage === this.props.images.length - 1) return null;

			return _react2['default'].createElement(_componentsArrow2['default'], {
				direction: 'right',
				icon: 'arrowRight',
				onClick: this.gotoNext,
				title: 'Previous (Right arrow key)',
				type: 'button'
			});
		}`

**Comment by benhowell** [comment]
This is fixed in master (see  #108 #109 https://github.com/jossmac/react-images/blob/master/src/Lightbox.js#L125). 

Other option is to wait for 0.5.3 to be released.

**Comment by denissonpaz** [comment]
Thank you very much!

I'll wait for the next release.

Denisson Paz
