### ISSUE TITLE
Prep for React v16 and removal for deprecation warnings (PropTypes & createClass)

### ISSUE THREAD

**Issue by padsbanger** [jossmac/react-images#132]
Are there any plans to prepare for React v16 as per this post: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

It means replacing all React.PropTypes and using the prop-types package, and replacing all React.createClass using the create-react-class package.

Doing this will also remove the deprecation warnings for anyone using React v15.5.0 which show in the console in development env.

**Comment by neptunian** [comment]
I just merged this request but a dependency, react-scrolllock (same owner) will still cause warnings to be thrown.

**Comment by kachkaev** [comment]
@neptunian could you please keep this issue open until there is a fix upstream? This will help people find a discussion of what they are looking for.

**Comment by damiangreen** [comment]
It appears a fix has been made, but the dependency needs bumping
 "react-scrolllock": "^1.0.6"
