### ISSUE TITLE
Can you use Blob or other controls?

### ISSUE THREAD

**Issue by liviuignat** [jossmac/react-images#133]
Hi,

1. Is there any way of showing Blob?

2. Is there any plan to add support for other components, instead of just images? Like `Pdf Viewer` for example?

Thanks

**Comment by neptunian** [comment]
I don't think this library will support that but issue #54 once it gets created could possibly allow any content.

**Comment by liviuignat** [comment]
@neptunian allowing any content would be an awesome feature. Thanks!
