### ISSUE TITLE
backdropClosesModal interferes with thumbnail click 

### ISSUE THREAD

**Issue by Matzu89** [jossmac/react-images#135]
Just walked into this one. Showing thumbnails but also want users to be able to close using backdrop. When clicking thumbnail, modal closes. Maybe prevent with `evt.stopPropagation()`?

**Steps to reproduce the behavior:**
- Add thumbnails
- showThumbnails = true
- backdropClosesModal = true
- Click thumbnail

**Expected behavior:**
- Thumbnail function triggers -> it does
- Modal stays open

**Actual behavior:**
- Thumbnail function triggers -> it does
- Modal closes

**Comment by twitchett** [comment]
Hmm, I've got that setup [here](https://twitchett.github.io/gallery/) but don't have the behaviour you describe.

Though I would add that clicking the current image closes the window - I would expect it not to.

**Comment by shssoichiro** [comment]
I've also experienced this behavior, but with the `onImageClick` event. `backdropClosesModal` overrides the `onImageClick` event so that the image closes whether I click the image or the backdrop.

**Comment by benhowell** [comment]
I'm not able to reproduce the original issue but I can confirm the latter. i.e. `backdropClosesModal` overrides `onImageClick`. Further, supplying a custom `onImageClick` function with `event.preventDefault()` and `event.stopPropagation()` allows `onClickImage` to function properly but disables `backdropClosesModal`.

**Comment by neptunian** [comment]
@Matzu89 @shssoichiro Simply add `event.stopPropagation();` to your onClickImage callback.  I will update he demo so people don't copy the incorrect code in their own app.
