### ISSUE TITLE
Multiline caption pushes close button off screen

### ISSUE THREAD

**Issue by twitchett** [jossmac/react-images#136]
First of all thanks for the great work on this! Definitely the best lightbox component for React that I've found. :)

**Steps to reproduce the behavior:**
Ensure `showCloseButton` is `true` and insert a caption with a linebreak.
Open image in lightbox (resize window if it doesn't reach the top of the screen).

**Expected behavior:**
All elements are visible on screen

**Actual behavior:**
The close button is pushed off the top of the screen, so the lightbox cannot be closed. I guess this is a problem with the way the image is resized to fit the screen, and it doesn't take the full height of the caption into account.

Obviously this is particularly problematic for large images/small screens when you cannot just resize the window. In the meantime I just set the modal to close on backdrop click.

**Comment by neptunian** [comment]
sorry i associated this commit with the wrong issue

**Comment by neptunian** [comment]
and didn't mean to close it.

**Comment by neptunian** [comment]
no, the size of the image does not get calculated based on the caption height.  the caption is meant to ideally be short and fit on one line.  i'd prefer to restrict the height of the caption so it doesn't push the arrow up or add an overflow hidden with an ellipsis or something so it can't wrap to multiple lines.
