### ISSUE TITLE
Image transitions

### ISSUE THREAD

**Issue by twitchett** [jossmac/react-images#137]
Hi @jossmac. I was thinking it would be really neat to have the option to animate the images in and out when the left/right arrows are clicked. Likewise for some sliding effects for the paginated thumbnails.

Is there a plan to introduce this feature, or do you have an opinion on how it should be implemented?

**Comment by twitchett** [comment]
I'm not much of a CSS wizard but I've been playing around and have a semi working solution for the main image animation, using [react-transition-group](https://github.com/reactjs/react-transition-group). I could fix it up and submit a PR, if that sounds good?

**Comment by zlouis** [comment]
This would be a huge help. I'd like to see an implemented fade option between photos.

**Comment by jossmac** [comment]
@twitchett @zlouis this isn't something we can achieve in v0.x but will be addressed in v1, please see #199

* * *

I'm closing this issue for now, please add a comment if you need it re-opened.
