### ISSUE TITLE
Uncaught Error: Cannot find module 'prop-types'

### ISSUE THREAD

**Issue by FusionDesign** [jossmac/react-images#143]
**Steps to reproduce the behavior:**
1. Install the very latest version using bower (based on git hash):
bower install https://github.com/jossmac/react-images.git#64f6b6f341d2dd199a4d93179870e518ba64ca60 --save

2. PropTypes was separated from the main React package and throws an error.

**Expected behavior:**
No errors in console.

**Actual behavior:**
react-images.js:1 Uncaught Error: Cannot find module 'prop-types'
    at s (react-images.js:1)
    at react-images.js:1
    at Object.<anonymous> (react-images.js:2868)
    at Object.41../components/Arrow (react-images.js:3269)
    at s (react-images.js:1)
    at e (react-images.js:1)
    at react-images.js:1
    at react-images.js:1
    at react-images.js:1

**Comment by neptunian** [comment]
@FusionDesign  

<img width="1256" alt="screen shot 2017-06-02 at 9 39 11 am" src="https://cloud.githubusercontent.com/assets/1676003/26715854/8807b66c-4777-11e7-80a9-634fd330fa51.png">

I ran that command and did not receive any errors. Make sure to do an npm install?

**Comment by FusionDesign** [comment]
It seems your example application uses a common.js file which includes the proper functions (checkPropTypes(), etc). This issue appears to be only be valid if you are using a build pipeline (such as Gulp) to bring in React & ReactDOM. 

My process is this:
1. Use gulp to compile vendor libraries (jQuery, React, ReactDOM, Bootstrap) into one vendor.js file.
2. Also use gulp to squash and concat plugin libraries (React Bootstrap, React Select, React Images) into plugins.js.
3. Require vendor.js and plugins.js in views. This is when the error is thrown.

**Comment by neptunian** [comment]
@FusionDesign prop-types is being listed as a dependency in package.json and is being properly imported where needed.  So i'm not sure what else can be done to fix this.

**Comment by FusionDesign** [comment]
I got around this by looking at the package.json file and including things directly instead of compiling your package into the plugins.js file.

import Gallery from '../../../bower/bower_components/react-images/examples/src/components/Gallery';
import Lightbox from '../../../bower/bower_components/react-images/lib/Lightbox';

**Comment by neptunian** [comment]
hi @fusiondesign .  i ran into your issue while trying to create a codepen using the /dist files which i think is what Bower uses.  I was able to reproduce your error and it should be fixed in this commit: https://github.com/jossmac/react-images/commit/8e186d164df6c7266c0660cfce5dd560b013ab0b
