### ISSUE TITLE
support default image when failing

### ISSUE THREAD

**Issue by khenlevy** [jossmac/react-images#149]
currently when passing image which not found it displays 'X'.
is there a way to configure a default image when an error occurred?

**Comment by neptunian** [comment]
You can test your own images in your app and cache them.  If any of them load with an error then perhaps you can pass in a different image.  I don't think it is the job of the Lightbox to detect this.
https://stackoverflow.com/questions/9815762/detect-when-an-image-fails-to-load-in-javascript
