### ISSUE TITLE
Is there a way to add Custom Class to the component

### ISSUE THREAD

**Issue by karan3112** [jossmac/react-images#150]
Is there a way to add custom class to the `Lightbox` component? Was finding it a little rigid to customize the look and feel using the `theme` property.

**Comment by pixelize** [comment]
Looking for the same feature, it seems theres is a PR open for that 
https://github.com/jossmac/react-images/pull/145

**Comment by olivierpichon** [comment]
I agree, also as HTML does not honour EXIF, to see images with the correct orientation is impossible if styles are not customisable

**Comment by neptunian** [comment]
this issue would be resolved by https://github.com/jossmac/react-images/issues/54
