### ISSUE TITLE
Lightbox closes when image clicked when backdropClosesModal = true

### ISSUE THREAD

**Issue by benhowell** [jossmac/react-images#152]
**Steps to reproduce the behavior:**
Set `backdropClosesModal = true`
Click on image in lightbox.

**Expected behavior:**
Lightbox shouldn't close.

**Actual behavior:**
Lightbox closes.

**Further info**
It appears that `backdropClosesModal` overrides `onImageClick`. Further, supplying a custom `onImageClick` function with `event.preventDefault()` and `event.stopPropagation()` allows `onClickImage` to function properly but disables `backdropClosesModal`.

This issue has been indirectly reported previously here: https://github.com/jossmac/react-images/issues/135

**Comment by neptunian** [comment]
I tested this and overrriding of onClickImage doesn't seem to actually happen however the image is indeed closing when backdropClosesModal is set to true and you click on the image.  Adding `event.stopPropagation()`; in the onClickImage handler fixed this for me.  I will update the demo code.

**Comment by benhowell** [comment]
That handler is optional though so it needs to be handled in cases where that prop is not supplied.

**Comment by neptunian** [comment]
@benhowell i don't know if this is very important.  if the user doesn't want to pass in an onClickImage handler then clicking it will just close it.  if they don't want that to happen they can just pass in a handler that stops propagation.  otherwise i'll need to detect what was clicked from where and it seems unnecessary for this edge case.

**Comment by neptunian** [comment]
let me know if that looks ok.  this also resolved #155.  seemed liked the cleanest/safest way to only target the backdrop click.

**Comment by benhowell** [comment]
I haven't tested but the logic seems correct to me. Personally, the route I'd take would be to have a default prop for the `onClickImage` func containing a call to `event.stopPropagation()` to prevent the `onClick` func of `Container` being triggered. If one were to chose to provide their own `onClickImage` function, they would also need to provide `event.stopPropagation()` if they didn't want the backdrop to be closed. A third option would be to always call `stopPropagation` and if a custom `onClickImage` were provided to just call that prior to calling `stopPropagation`. 

Anyway, whatever works, works. :+1:

**Comment by neptunian** [comment]
@benhowell yes but then that wouldnt solve #155 or any other items the user might click on that is within the container.
