### ISSUE TITLE
Long Caption makes the figure container hide the backdrop

### ISSUE THREAD

**Issue by AfzalH** [jossmac/react-images#156]
**Steps to reproduce the behavior:**
Open an image with a large caption so that it fills the entire width of the screen

**Expected behavior:**
The caption should be aligned with the image so that backdrop area is clickable (for closing lightbox).
Expecting caption like 'magnific popup' (multiline scrollable caption)
**Actual behavior:**
The caption area expands the container element (figure element) so it covers the entire width of the screen making the backdrop area un-clickable.

**Comment by neptunian** [comment]
fixed in commit ac935b0ecf574759b8f80a7add3f4e14015e5ef8
caption will still extend to width of screen but will not interfere with backdrop closing

**Comment by AfzalH** [comment]
Great! Appreciate your effort!
