### ISSUE TITLE
Sizes attribute has an hard-coded value

### ISSUE THREAD

**Issue by am** [jossmac/react-images#159]
**Steps to reproduce the behavior:**
Use the `srcset` to define some images. Check the html output and see that sizes has a hardcoded value of:
```html
<img sizes="100vw" />
```
**Expected behavior:**
Be able to set the `sizes` dynamically.

**Actual behavior:**
`sizes` has a hardcoded value of `100vw`

**Comment by jorrit** [comment]
Aren't images supposed to be displayed at 100vw ?

**Comment by am** [comment]
Hi @jorrit , I think you are right. A Lightbox should always be `100vw`... or I may be doing something wrong. Closing this for now. Many thanks for clear up things.
