### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kof** [jossmac/react-images#16]
Disclaimer: I probably didn't spend enough time, feel free to ignore if something is not true. Also my language below is very strict forward, don't take it as "rude".

## General

- not consistent es6 usage (createClass)
- prefer const, eslint has an option for it http://eslint.org/docs/rules/prefer-const.html
- don't put generated files into repository, put them into npm package
- this can also be static https://github.com/jossmac/react-images/blob/master/src/Lightbox.js#L229
- is it deep cloning, why? https://github.com/jossmac/react-images/blob/master/src/Lightbox.js#L25
- icons could be in svg format on file system, webpack can convert them to the js string

## Related to JSS

1. As react-images is a lib, you should not use jss singleton instance, create your own: https://github.com/jsstyles/jss#create-an-own-instance-of-jss
Normally in such cases I create a local jss module where  I create the instance, do the setup, export useSheet function and use this module in all other components.
1. you could use useSheet as a decorator
1. you can do the same without any helper:
https://github.com/jossmac/react-images/blob/master/src/Lightbox.js#L109
  ```
  <button className={`${classes.some} ${classes.some2}`}>test</button>
  ```
1. instead of using one big style file and one big Lightbox class, you should split it into different small classes.
1. vendor prefixes for userSelect are handled by the prefixer plugin you are already using, not sure about touchCallout, try it out. https://github.com/jossmac/react-images/blob/master/src/styles/default.js#L131
1. I ended up in puting style file at the same directory level as the componet using it. For e.g. Lightbox.js, lightboxStyle.js

**Comment by jossmac** [comment]
This is great, thanks @kof
