### ISSUE TITLE
Caption containing a link

### ISSUE THREAD

**Issue by angieyu** [jossmac/react-images#161]
**Steps to reproduce the behavior:**
 images={[{
                    src: 'https://s3-media1.fl.yelpcdn.com/bphoto/wBkBzubvfdQBW3M65cxdCw/ls.jpg',
                    caption: 'Sydney, Australia - Photo by Jill Smith window.redirect(www.google.com)'
                }, {src: 'https://4.bp.blogspot.com/-mUbv81BZwbY/VPc-6xUzzvI/AAAAAAAAFCw/pDqvGuVytWA/s1600/0403.jpg'}]}

**Expected behavior:**
I would like the caption to be able to contain a link to an external site.

**Actual behavior:**
The link is just displayed as text

**Comment by d7laungani** [comment]
Have you found a solution to your problem ? I am having the same issue.

**Comment by angieyu** [comment]
I am still having the same issue... @d7laungani any luck?

**Comment by anhkhoi** [comment]
The same issue for me, I think I and someone else will need this feature too.

**Comment by uturnr** [comment]
My workaround for now is to use `customControls` to display a JSX element based on the `currentImage`. This will show in the top left corner instead of the bottom left.

```
  render(){

    const photos = [
      {
        src: 'http://imgsv.imaging.nikon.com/lineup/lens/zoom/normalzoom/af-s_dx_18-140mmf_35-56g_ed_vr/img/sample/sample1_l.jpg'
      },
      {
        src: 'http://coolwildlife.com/wp-content/uploads/galleries/post-3004/Fox%20Picture%20003.jpg'
      }
    ];

    const controls = [
      <a key="0" href="http://www.google.ca">Photo 1</a>,
      <a key="1" href="http://www.github.com">Photo 2</a>
    ];

    return (
      <div>
      <a href="#" onClick={this.openLightbox}>TEST</a>
      <Lightbox
        customControls={controls[this.state.currentImage]}
        images={photos}
        onClose={this.closeLightbox}
        onClickPrev={this.gotoPrevious}
        onClickNext={this.gotoNext}
        currentImage={this.state.currentImage}
        isOpen={this.state.lightboxIsOpen}
      />
      </div>
    );

  }
```

**Comment by jossmac** [comment]
@angieyu @d7laungani @anhkhoi @uturnr I'm sorry that you've had this issue.

**Solution today**

Though not well documented, the caption property supports `string | element` so you should be able to pass through something like:

```jsx
[
  {
    src: 'https://website.com/image-1.jpg',
    caption: <span>Sydney, Australia - Photo by <a href="www.google.com">Jill Smith</a></span>
  },
  {
    src: 'https://website.com/image-2.jpg',
  }
]
```

**In the future**

In v1 of this package (see #199) you'll have the ability to replace any of its components, in this case you could augment the `<Footer />` to suit your needs.

I'd love to hear your thoughts on the rewrite,
Joss

* * *

I'm closing this issue for now, please add a comment if you need it re-opened.
