### ISSUE TITLE
Accept .MP4 (movies) on lightbox

### ISSUE THREAD

**Issue by MatheusMorett2** [jossmac/react-images#163]
**Steps to reproduce the behavior:**
Put a SRC witch the extension is .mp4
image shows broken

**Expected behavior:**
Accept movies in lightbox...

**Actual behavior:**
Waiting...

**Comment by foodaka** [comment]
is this a feature request or is it capable to accept video?

**Comment by UsmanJ** [comment]
Does lightbox accept videos?

**Comment by vfonic** [comment]
I believe this is a feature request. Would be good to hear from project maintainers.

/cc @jossmac @neptunian

**Comment by neptunian** [comment]
I'm not really interested in working on video support as I see this as an image viewer but if someone has a PR with a simple solution i'm open to it.

**Comment by jossmac** [comment]
@MatheusMorett2 @foodaka @UsmanJ @vfonic I'm sorry it's taken me so long to address this.

Video support in v0.x is not something we're able to support. The good news is that I've rewritten the package from the ground up so you can achieve this and more!

There's notes and features detailed in this issue #199 and you can checkout the [v1 branch](https://github.com/jossmac/react-images/tree/v1). I'd love to hear your thoughts on the approach taken in v1 🙂

Cheers,
Joss

* * *

I'm closing this issue for now, please add a comment if you need it re-opened.
