### ISSUE TITLE
Couldn't render this component

### ISSUE THREAD

**Issue by strangewolf** [jossmac/react-images#164]
I have followed all the steps.

import Lightbox from 'react-images';

in my render function:

render(){
 <Lightbox isOpen={this.state.lightbox} onClickImage={()=>this.openLightbox()} images={IMAGES} onClose={()=>this.onClose()} onClickPrev={()=>this.gotoPrevious()} onClickNext={()=>this.gotoNext()} />
}

output is like:
react-empty: 119 

i dont know what is the issue.. please help me.

**Comment by neptunian** [comment]
Please go into the Gitter chat for help troubleshooting your code.

**Comment by simbawus** [comment]
@strangewolf Hello, did you have solve this problem？
