### ISSUE TITLE
Accept string values for width

### ISSUE THREAD

**Issue by JapMul** [jossmac/react-images#165]
**Steps to reproduce the behavior:**
Set width to `width='50%'`

**Expected behavior:**
`max-width` of the element will be set to 2%, **without** showing an error that the width can only be a number.

**Actual behavior:**
`max-width` of the element is set to 2%, but is showing an error that the width can only be a number.

**Comment by jossmac** [comment]
Hi @JapMul!

This seems like a reasonable feature, any chance you could provide a PR?

Thanks in advance,
Joss

**Comment by JapMul** [comment]
@jossmac Allright, I think I can provide a PR somewhere this week!
