### ISSUE TITLE
Reacy 16

### ISSUE THREAD

**Issue by theskillwithin** [jossmac/react-images#166]
react-images@0.5.6 requires a peer of react-dom@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-images@0.5.6 requires a peer of react@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.

**Comment by Shadowman4205** [comment]
@neptunian Hello i get this too, will be any updates?

**Comment by neptunian** [comment]
@Shadowman4205  yes going to try and to this today

**Comment by neptunian** [comment]
the latest release 0.5.7 should resolve these warnings
