### ISSUE TITLE
Unable to zoom (pinch) on mobile

### ISSUE THREAD

**Issue by tomfa** [jossmac/react-images#167]
Hi guys! Thanks for this delightful library. I'm showing rather large images on a new project, and many of them requires zooming (they're mostly of old texts). However, I can't manage to do this on my Nexus 5X or Xiaomi mi5 (Chrome)

**Steps to reproduce the behavior:**
- Go to http://jossmac.github.io/react-images/
- Click to open lightbox mode
- Pinch to zoom in on image (i.e. native browser zoom)

**Expected behavior:**
- Zooms

**Actual behavior:**
- No zoom happens

**Comment by jossmac** [comment]
@tomfa thanks for the heads up. I'll check it out 👍

**Comment by JosephFarina** [comment]
Has there been any updates on this issue?

**Comment by kkshyu** [comment]
any updates about it?

**Comment by patelrr** [comment]
@jossmac Any update on this feature or issue?

**Comment by mhedengren** [comment]
Did anyone come up with a solution for this issue?

**Comment by patelrr** [comment]
Sample code - https://codesandbox.io/s/dazzling-goldberg-0u22t

Sample Output - https://0u22t.csb.app/

**Comment by davwheat** [comment]
I am definitely stealing that code! Thank you so much!

**Comment by davwheat** [comment]
I will be closing this in favour of #342 as that has more tags and recent comments.
