### ISSUE TITLE
Get dist file working as standalone

### ISSUE THREAD

**Issue by neptunian** [jossmac/react-images#170]
Trying to include react-min.js from /dist and gettng an error "cannot find module prop-types"

**Comment by jorrit** [comment]
Have you included the prop-types module before the react-images module?

**Comment by neptunian** [comment]
@jorrit  yes, if you actually look inside the min file it has a prop-types: undefined in there.  Here is a codepen: https://codepen.io/neptunian/pen/gGjgrp

I noticed the same thing happening in react-select which also used react-component-gulp-tasks to create a build.  they've since gotten rid of it and now have a standalone example. 

relates to https://github.com/jossmac/react-images/issues/143

**Comment by jorrit** [comment]
I see. I think leaving react-component-gulp-task behind is a good decision, it seems to not keep up with modern developments.

In this specific case I think the react/prop-type includes only work when you have a complete requirejs configuration in place in which you define the alias and the script.

I developed my [own](https://github.com/jorrit/react-hyper-responsive-table) react module using [nwb](https://github.com/insin/nwb) and I am satisfied with the experience.

**Comment by neptunian** [comment]
awesome, i'll check it out
