### ISSUE TITLE
Upgrade react-transition-group to v2

### ISSUE THREAD

**Issue by snags88** [jossmac/react-images#176]
Trying to upgrade react to v16 and move react-transition-group to v2, but this library has a dependency on `react-transition-group` v1.

This would be a breaking change so I'd be interested in hearing thoughts of keeping this at v1 or moving up to v2.

**Comment by neptunian** [comment]
@snags88 that's fine to upgrade, feel free to make a PR.

**Comment by rickerd** [comment]
I've updated it in my PR https://github.com/jossmac/react-images/pull/196

**Comment by jossmac** [comment]
@snags88 please see #199 

The rewritten package uses v2 of react-transition-group, which will be great when released, though whilst we'll fix bugs with v0 there won't be any additional enhancements/features.
