### ISSUE TITLE
Please no breaking changes in patch versions

### ISSUE THREAD

**Issue by liviuignat** [jossmac/react-images#177]
Hi guys,

- You really should not add breaking changes in patch versions. We were using react-images inside a library that is referenced in another project. 
- In the main project `yarn.lock` was deleted and regenerated
- All of the sudden `react-images` was upgraded from `0.5.5` to `0.5.11` and lost some valuable time tracking this. 

To solve it we had just to change from `import * as LightBox` to `import Lightbox`, but the difficulty was that React was not clear about what component failed, and we had a lot of components on that page, inside multiple components packages.

The way you export your main library is a breaking change and should have been used a "minor" version, eg `0.6.x`.

Feel free to close this. Keep up the good work ;)

Cheers,

**Comment by jschneier** [comment]
Similarly the peer dependency was upgraded from 0.5.6 to 0.5.7

**Comment by neptunian** [comment]
@liviuignat  that slipped my mind, sorry about that!
