### ISSUE TITLE
New default look and feel

### ISSUE THREAD

**Issue by neptunian** [jossmac/react-images#178]
<img width="1257" alt="photo-viewer" src="https://user-images.githubusercontent.com/1676003/33445729-b0127bee-d5f5-11e7-858f-62ea68ff6582.png">

How would people feel about changing the look to be more like Google Photos/500px viewer.  Letting the image take up full height and having the UI hide/show on mouse movement or a tap on touch devices to reveal the entire photo.  I think it would be a nicer way to view the photos without clutter.  A major benefit would be that his is exactly how you'd want fullscreen view to function so triggering that on a mobile device would be easier as more code for separate mobile/desktop styles, layout, and functionality would be very minimal.

When some people think of a "Lightbox" they think of something more like a modal with an image and a light overlay.  I'm thinking more of an image viewer that really focuses on the image so I might just create a fork or start anew on something catered more towards photography if this seems inappropriate.

**Comment by jorrit** [comment]
Perhaps the rendering logic and the remaining code can be separated so the look and feel are pluggable?

**Comment by neptunian** [comment]
@jorrit its "themeable" currently but no option to swap out all of it.  even so i still think this is a much more functional layout especially to enable fullscreen capability.

**Comment by jossmac** [comment]
@neptunian does the replaceable component architecture of `v1` resolve this issue?

**Comment by neptunian** [comment]
@jossmac i think it would but i still think the default look and style that is currently being used looks very 10 years ago.

**Comment by mkalygin** [comment]
@neptunian hmmm, I'm thinking on experiment with this one. I love this UX with showing UI controls on mouse move or touch. Similar solution Flickr has in the fullscreen mode. But I have a couple of questions:

- What are your thoughts on where to place thumbnails if they are enabled?
- And pic caption with pic count?
- Should we expose theming for "shading" colors or should it be black with white text (this is a gradient background for UI controls on mouse move or touch)?

**Comment by neptunian** [comment]
I think for those who wants thumbnails at the bottom they can either overlay at the bottom of the photo or there will be extra black space made to accompany it.  They can be very tiny thumbnails, like on Flickr, that grow only when you hover over them so they don't take up too much space by default.

The caption and other stuff would be similar.  Perhaps an option to have it always present or only when the user first gets to the photo.  For example you see the photo and the caption and other info appear, overlayed, then disappear after a couple of seconds.  They reappear on mousemove or tap.  Then the user goes to the next photo and that repeats.

I don't think its necessary to have theming but i could see someone maybe wanting a white background, so perhaps that would be necessary.

**Comment by jossmac** [comment]
Hi folks!

Having a bit of trouble getting something online so I've created this gif to get the ball rolling:

![react-images-v1](https://user-images.githubusercontent.com/2730833/36199049-7e4706d0-11cc-11e8-87a4-60a564dae303.gif)

Let me know what you think!

**Comment by mkalygin** [comment]
@jossmac this is awesome. 👍Is it v1?
