### ISSUE TITLE
Store as .svg and convert to string

### ISSUE THREAD

**Issue by jossmac** [jossmac/react-images#18]
Consider https://developer.mozilla.org/en-US/docs/XMLSerializer via #16

**Comment by shmuga** [comment]
I think best way is to use webpack like file loading.
This [plugin](https://github.com/hughsk/svgify) can help you with this, but currenly you can't load custom transformation to browserify as I understand, so you need first to make `react-component-gulp-tasks` customizable. We can try to send pr to this module to add support of custom transformations somehow :smile:

**Comment by jossmac** [comment]
@shmuga thanks for your feedback

I don't really want to lockout Browserify users. After thinking about it for a while, considering that the idea is for this package to be simple and lightweight, the addition of another module to transform SVG (which i've already done manually) seems unnecessary

Image assets should probably be themeable; I'll get back to this later
