### ISSUE TITLE
CONTRIBUTING.md missing

### ISSUE THREAD

**Issue by jimt** [jossmac/react-images#182]
http://jossmac.github.io/react-images/ refers to a **CONTRIBUTING.md** file, but it doesn't exist in the gh-pages branch, resulting in a GitHub 404 page.

`<p>If you find a bug, please read the <a target="_blank" href="https://github.com/jossmac/react-images/blob/master/CONTRIBUTING.md">Contribution Guildelines</a> before you <a target="_blank" href="https://github.com/jossmac/react-images/issues">report the issue</a>.</p>`

**Comment by jossmac** [comment]
Ugh, I moved it to the `/.github` directory 😔

Thanks for the heads up, I'll get on this!
