### ISSUE TITLE
React 16 without warnings

### ISSUE THREAD

**Issue by apepper** [jossmac/react-images#184]
**Steps to reproduce the behavior:**

Use the current version of `react-images` (`0.5.13`) together with `react` 16 (e.g. `16.2.0`). Call `npm install`.

**Expected behavior:**

Both packages should simply install without warnings.

**Actual behavior:**

Npm will print the following warning:

```
npm WARN react-scrolllock@1.0.9 requires a peer of react@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.
```

**Possible fix:**

`react-scrolllock` in version `2.0.0` seems to have fixed the issue (see https://github.com/jossmac/react-scrolllock/issues/12 ). But `react-images` still requires version `1.x` of `react-scrolllock` (see https://github.com/jossmac/react-images/blob/db5236d852009417215cc5f5eb29328c09eb583e/package.json#L16).

"Simply" make `react-images` work with `react-scrolllock` `2.0.0` and the warning should go away.

PS: Thank you for this great package. Images are looking really good with this package.

**Comment by StefanoPastore** [comment]
@jossmac any news on this?

**Comment by apepper** [comment]
@neptunian Thank you for merging #190! Sadly this didn't make it into the `0.5.15` release (according to Github 5 minutes to late). Can you do a `0.5.16` release, so we can profit from React 16?
