### ISSUE TITLE
Doubt about using this component

### ISSUE THREAD

**Issue by albertoivo** [jossmac/react-images#185]
**Steps to reproduce the behavior:**

```
            <Lightbox
              images={[
                { src: '../images/photo1.jpg' },
                { src: '../images/photo2.jpg' }
              ]}
              currentImage={this.state.currentImage}
              isOpen={this.state.lightboxIsOpen}
              onClickImage={this.handleClickImage}
              onClickNext={this.gotoNext}
              onClickPrev={this.gotoPrevious}
              onClickThumbnail={this.gotoImage}
              onClose={this.closeLightbox}
            />
```
`All the functions and state were copied from github repo`

**Expected behavior:**

See the pictures in a gallera like the website

**Actual behavior:**

White page.

**Comment by jossmac** [comment]
Hi @albertoivo,

I'm sorry that you're having trouble, could you answer a couple of questions:

Do you have images locally that match those paths?

Also, do you have methods in your component matching those that are passed to the Lightbox?

**Comment by albertoivo** [comment]
Hello @jossmac thanks for your fast reply.

Yes, these images do exist. I also try with `sr: 'https://placekitten.com/200/300'`

About the methods, I copied them from [The Gallery.js from examples](https://github.com/jossmac/react-images/blob/master/examples/src/components/Gallery.js)

 only change `images={this.props.images}` to my code in the first comment.

**Comment by jossmac** [comment]
Okay, no worries. Would you mind recreating the issue in https://codesandbox.io

It'll be easier to diagnose the problem 🙂

**Comment by albertoivo** [comment]
Here as requested: `https://codesandbox.io/embed/mml05mpj49`
Thanks for the help

**Comment by neptunian** [comment]
@albertoivo the problem is you are not ever calling the "openLightbox" method which you define in your portfolio component so the lightbox component never gets mounted.
