### ISSUE TITLE
Image goes up when you close lightbox

### ISSUE THREAD

**Issue by pixelize** [jossmac/react-images#19]
Hi Joss,

You're component is wonderful, I've just integrated into one of my React project.
Btw, I got a visual bug when the lightbox is open

When you want to leave the lightbox (using ESC or clicking on the cross) the image goes up.
It seems that appears only if you have scroll in the web page. I think it is caused by the overflow which is applied on <body>. Do you know anything that could fix that bug please ?

There is an example in video : 
https://vid.me/xh59

Thanks in advance.

**Comment by jossmac** [comment]
@pixelize thanks for the description and video - made it really easy to diagnose :)

Fixed in `0.3.1`

**Comment by pixelize** [comment]
Thanks for quick answer, will update and let you know how it's going :)
