### ISSUE TITLE
Missing default behavior for event handlers?

### ISSUE THREAD

**Issue by chrismv48** [jossmac/react-images#192]
After installing this library and starting to use it for the first time, I was surprised to realize that basic event handles like `onClose`, `onClickNext`, `onClickPrev` didn't have default behavior already implemented for me. In my experience, most libraries provide default behavior while providing the ability for users to override behavior by passing in their own props. I would expect such basic actions like what I mentioned above to already have default behavior implemented by the library -- why is this not the case?

**Comment by jossmac** [comment]
Hi @chrismv48, you make a good point!

> why is this not the case?

The original implementation actually handled state. At the time though, there was a movement in the react community for library creators to facilitate events via props and not maintain any state internally. In hindsight I could have shipped a "stateful" version of the package.

**Looking to the future**

In the rewrite of this package (see #199) state is again handled internally and accessible to consumers via `onChange` handlers. I think this the best of both worlds.

I'd love to hear your thoughts,
Joss
