### ISSUE TITLE
Add localization support for button captions of the thumbnail viewer

### ISSUE THREAD

**Issue by kripod** [jossmac/react-images#193]
The captions of the thumbnail viewer are not localized by `leftArrowTitle` and `rightArrowTitle`. I found the following 2 lines of code for further reference:

- https://github.com/jossmac/react-images/blob/1241e81d877655cab78aa4ea3edb4e2bc258d260/src/components/PaginatedThumbnails.js#L107
- https://github.com/jossmac/react-images/blob/1241e81d877655cab78aa4ea3edb4e2bc258d260/src/components/PaginatedThumbnails.js#L124

**Comment by jossmac** [comment]
@kripod v1 will allow consumers to replace any component, please see #199

**Comment by jossmac** [comment]
Closing this for now, please comment if you'd like it reopened.
