### ISSUE TITLE
Theme paginatedThumbnails

### ISSUE THREAD

**Issue by qradle** [jossmac/react-images#194]
Hi.
I've done some css customization through theme prop and i found out that paginatedThumbnails styles doesn't set to PaginatedThumbnails component. It always uses default props.

**Comment by rickerd** [comment]
Fork it, change it and make a PR if you need it.
It has to do with src/components/PaginatedThumbnails.js.

In src/components/Footer.js there is const classes = StyleSheet.create(deepMerge(defaultStyles, theme)); what makes the default style and theme merging. Maybe you can take a look at that part.

**Comment by rickerd** [comment]
Sadly not I think.
I also forked it and changed the thing to my needs.

You would never ever want to put the source code hardcoded info your project.

I hope you’ll figure it out my female programmer 🤗
Or change the code itself to fit your needs to be able to use themes. But that is very much work I think.

**Comment by ktriviso** [comment]
Thanks so much for getting back to me so quickly! Looks like I'll have to fork and change it as well.

**Comment by rickerd** [comment]
I did the same back then 😅
But seeing your website you don’t have alot of trouble changing the code.

Damn you’re great. Have a nice day/evening.
