### ISSUE TITLE
Height is not controllable

### ISSUE THREAD

**Issue by nidhi-tandon** [jossmac/react-images#197]
The image should adjust itself according to the screen and the browsers navigation bar
![screen shot 2018-01-22 at 12 28 09 pm](https://user-images.githubusercontent.com/6941627/35208879-7cf4f850-ff70-11e7-89cf-41b2f1a8477b.png)

Actual behaviour: the captions gets cut in mobile screen
![screen shot 2018-01-22 at 12 27 22 pm](https://user-images.githubusercontent.com/6941627/35208871-76176aa4-ff70-11e7-8d49-a29739a25d44.png)
I will be very thankful to anyone for help. Really got stuck. no external styling is working and not able to override the internal styling

**Comment by jossmac** [comment]
@nidhi-tandon v1 will allow consumers to replace any component, please see #199
