### ISSUE TITLE
React Images v1 🎉

### ISSUE THREAD

**Issue by jossmac** [jossmac/react-images#199]
For the past few months I've been rewriting `react-images` from the ground up. Having solidified some of the core concepts, i'd really like to hear your thoughts 🙂

> [Check out the v1 branch -->](https://github.com/jossmac/react-images/tree/v1)

The main impetus for rewriting this library was providing consumers with the building blocks necessary to create *their* component. Need extra buttons in the header? No problem, import react-images' <code><Header&nbsp;/></code> component and enhance it. Need to render videos rather than images? No problem, replace the <code><View&nbsp;/></code> component and pass the data required to the `views` property.

**General notes:**

- At the moment the v1 branch is just a `create-react-app` until we decide on a build setup
- Much of the state is now internal, simplifying implementation for the consumer
- This project now leverages the amazing [react-view-pager](https://github.com/souporserious/react-view-pager
), which takes care of the touch/swipe boilerplate via [react-motion](https://github.com/chenglou/react-motion)
- A great deal of the component architecture has come from recent R&D with @JedWatson for version two of [react-select](https://github.com/JedWatson/react-select/tree/v2)

**Features of v1:**

- 🛠 &nbsp; Comprehensively typed ([flow](https://flow.org/))
- 📱 &nbsp; Support for touch devices
- 📺 &nbsp; Fullscreen support on desktop devices
- 🖼 &nbsp; Carousel without modal dialog
- 🏖 &nbsp; No restrictions on data shape
- 🚀 &nbsp; Replaceable component architecture

Many of the requirements, issues, and feature requests should be addressed by the new customisable component architecture without requiring changes to the core.

**What this means for v0.x**

No need to worry. I, together with @neptunian (the primary maintainer, who's doing an amazing job!), will continue to release critical bug fixes. We won't however be implementing enhancements or new features unless provided in a rock-solid PR.

The new API is a massive departure from v0.x, so there won't be an "upgrade guide" as such. I'll endeavour to provide a handful of examples to cover most use-cases and welcome anyone else to do the same.

**Still left to do:**

- [x] settle on and implement a build tool
- [ ] unit tests for each component
- [ ] integration tests for carousel/modal
- [x] lockdown the API and release an alpha
- [x] light-weight theming/styling for components
- [x] add classnames for those who prefer styling with CSS
- [x] default components implement ARIA best practices

I'd like to thank everyone who has contributed to this project over the years, without your support react-images wouldn't be where it is today. Cheers to the open source community 💖

Looking forward to your feedback!

**Comment by jorrit** [comment]
Congrats! Which build systems have you considered so far.

**Comment by jossmac** [comment]
Thanks!

Will likely port the build system from React Select, which uses [Rollup](https://rollupjs.org/).

NB: [Parcel](https://parceljs.org/) looks promising but may not yet be mature.

**Comment by jorrit** [comment]
It would benefit testing if v1 could be published to npm with a beta or alpha version number and the `next` tag. See https://docs.npmjs.com/getting-started/using-tags.

**Comment by codeluggage** [comment]
@jossmac Is there a way we can help test this? What is the recommended way to use the `v1` branch instead of the npm package, as it stands today? 

Super excited about this! 🎉

**Comment by jossmac** [comment]
### Update

Checkout the demo site: [v1 Alpha Demo -->](http://bit.ly/react-images-v1)

Alpha releases of `react-images@1.0.0-alpha.x` available on npm:

```bash
yarn add react-images@next
```

CC @jorrit @codeluggage

**Comment by benhowell** [comment]
Hi @jossmac,
I'm not seeing the examples at the bottom of the page...

**Comment by benhowell** [comment]
Works ok in Chromium on Linux but not FF. Quick inspection shows that each
thumb in the gallery with class .css-1vnvkj1 has a height of zero.

**Comment by benhowell** [comment]
Not proposing this as a solution but I've just hacked it so it works in FF
by removing position:absolute; from the image class .css-3c3ju2 (might give
you an idea at least)!

**Comment by jossmac** [comment]
@benhowell cheers mate, fixed now! `glam` and `flex` weren't playing nice.

Also added prop type documentation 💃

**Comment by michalica** [comment]
Wha about this? 
const images = [{ src: 'path/to/image-1.jpg', src: 'path/to/image-2.jpg' }];

You define array of images in doc in this way.

**Comment by weslleyaraujo** [comment]
`yarn add react-images@next` is currently failing for me 😩

```
Module not found: Can't resolve 'react-images' in '...'
```

Looking at `node_modules/react-images/package.json` I got

```js
{
  "version": "1.0.0-alpha.1",
  "main": "lib/index.js",
  "jsnext:main": "dist/react-images.es.js",
  "module": "dist/react-images.es.js",
}
```

There is no lib or dist directory, only src is there.. maybe something is missing on the publish script?

**Comment by damienbrz** [comment]
@weslleyaraujo I'm having the same issue.

**Comment by neptunian** [comment]
@codeluggage @damienbrz @weslleyaraujo the files should be on NPM now

**Comment by kachkaev** [comment]
@neptunian should the version be `1.0.0-alpha.2` instead of `1.0.1-alpha.1`? 🤔

**Comment by neptunian** [comment]
@kachkaev i was wondering that myself

**Comment by neptunian** [comment]
@kachkaev you're right, i'll fix that

**Comment by kripod** [comment]
@neptunian Unfortunately, the `lib` folder is still not published in `1.0.0-alpha.2`.

**Comment by ArVan** [comment]
@neptunian just installed the alpha version and the lib folder is not there.

**Comment by neptunian** [comment]
@ArVan @kripod please use `yarn add react-images@next`

**Comment by janklimo** [comment]
`1.0.0-alpha.3` working great for me 👍

**Comment by kripod** [comment]
Unfortunately, SSR is still not working (see #247 for further details).

**Comment by sergonius** [comment]
Ran into the SSR issue with Netlify as well.
The stable version has a nice little `canUseDom`.

**Comment by OriAmir** [comment]
@jossmac what about version 1? it's still 0.5.19 , still not 'swipe' on mobile...

**Comment by OriAmir** [comment]
@jossmac @neptunian 
it's looks like this library will not get support anymore ? no one answer here or on issues...

**Comment by neptunian** [comment]
unless there are any major issues with v1 i'd be happy to release it if @jossmac is okay with it.  I'm not sure Flow was the best decision over Typescript for typing but, perhaps that could be changed later.  What does everyone think? The only major issue that anyone seems to have brought up is the SSR issue which looks like an easy fix.

**Comment by iammatthias** [comment]
@jossmac @neptunian Will the SSR issue be fixed any time soon? It would be great if v1 could be released with SSR support.

**Comment by OriAmir** [comment]
> @jossmac @neptunian Will the SSR issue be fixed any time soon? It would be great if v1 could be released with SSR support.

I think that right now no one work on this library and the best option is to release v1 and then add improvements .

**Comment by OriAmir** [comment]
> Is there any plan to released this version ? I feel like nobody is taking care of this library anymore.
You right, no one cares about this library.
@jossmac @neptunian  If you don't want to support it anymore so give the keys to someone else that want to that.

**Comment by neptunian** [comment]
@OriAmir There hasn't exactly been any PRs to fix any issues with this so it wouldn't make much of a difference.  If someone would like make a PR for the SSR issue, that would be welcome.  Otherwise I'll have to get it to when I get a chance which should be soonish!

**Comment by OriAmir** [comment]
> @OriAmir There hasn't exactly been any PRs to fix any issues with this so it wouldn't make much of a difference. If someone would like make a PR for the SSR issue, that would be welcome. Otherwise I'll have to get it to when I get a chance which should be soonish!

@neptunian 
I think that the best option is firstly to release v1 and then fix the SSR and other issues because the library needs some refresh -there are many issues without replay and any new release not happened in the last 6 months.

**Comment by iammatthias** [comment]
@oriamir the SSR issue affects a lot of people who might use this library, considering how popular frameworks like Gatsby are becoming. 

If you want the current version released as a V1, what’s stopping you from using the alpha? Changing it from alpha to V1 doesn’t make any functional difference. 

Give the maintainers time to do their thing and live their lives. The great thing about this project being open-source is that nothing is stopping you from submitting a PR that fixes what you perceive to be an issue. 

@neptunian, thanks for the work you’ve put into this.

**Comment by neptunian** [comment]
if you install the latest next version (react-images@next), the SSR app should be fixed.

**Comment by neptunian** [comment]
I want to mention before the release of v1 that I do not plan to maintain v0.x.  I can create a branch for it, if anyone else wants to work on it, and accept PRs there.

**Comment by daydream05** [comment]
@neptunian  Thank you for the amazing work! And everyone here as well
