### ISSUE TITLE
Support for img srcset 

### ISSUE THREAD

**Issue by neptunian** [jossmac/react-images#2]
Any plans or interest to make the Lightbox more responsive by supporting 'srcset'?

**Comment by jossmac** [comment]
Last time I looked into `srcset` the browser coverage was really poor, though it seems to have improved http://caniuse.com/#feat=srcset

Would you be interested in submitting a PR?

**Comment by neptunian** [comment]
@jossmac Great!  I'll work on a PR.  Since browsers that don't support it will just use src, it should be harmless.

**Comment by jossmac** [comment]
@neptunian sounds good, I look forward to it

**Comment by neptunian** [comment]
@jossmac  Can I introduce some other kind of image placeholder tool rather than the fillmurray.com one?   With srcset I'll need to grab various sizes of the same image which fillmurray.com doesn't seem to support.  This website does however: http://lorempixel.com/  Or if you have any suggestions...

Also, I notice the thumbnails are simply larger photos being squashed down, so could update that, if desired, as well.

**Comment by jossmac** [comment]
@neptunian LoremPixel is a terrific service, can't wait to see the images you choose!

Good call on the thumbnails, i was pretty rushed when releasing the demo site, thanks mate :)

**Comment by jossmac** [comment]
Resolved by #6

**Comment by neptunian** [comment]
@jossmac  I hadn't updated the documentation yet in my branch that was merged.  Shall I do that?

**Comment by jossmac** [comment]
@neptunian sorry! Would you mind submitting a separate PR with docs?
