### ISSUE TITLE
Function preloadImage  in componentWillReceiveProps get old images

### ISSUE THREAD

**Issue by wsYdd** [jossmac/react-images#201]
When  initial  images  params empty list, then we set anther list and get error:Uncaught TypeError: Cannot read property 'complete' of undefined. Maybe the function preloadImage in componentWillReceiveProps get old images which is empty list ?

**Comment by neptunian** [comment]
did the latest release fix your issue?

**Comment by jossmac** [comment]
@wsYdd please checkout latest on npm `0.5.17` with the fix from #207.

* * *

I'll close the issue for now, please comment if you need it reopened.
