### ISSUE TITLE
New dependency react-spinners increases build size

### ISSUE THREAD

**Issue by apepper** [jossmac/react-images#202]
I tried out `react-images` in version `0.5.15` and `0.5.16`. Compared to `0.5.14` the resulting bundle size increase alot, adding ~90 kb of uglified, but not-gzipped payload.

One way to measure it, is this way:

**Steps to reproduce the behavior:**

* Call `yarn webpack --progress -p`

**Expected behavior:**

`app.js` should not be too big (ideally around ~190 kb, as with 3d48f4766112f7f93b6555b3b1907331bfcc0583)

**Actual behavior:**

`app.js` is quite big (currently ~277 kb, as with 7f229b1078ccba0b70a9b93e8ed03db903f40689)

It appears, that the biggest difference between those versions is https://github.com/jossmac/react-images/pull/187. That PR added a new dependency to http://www.davidhu.io/react-spinners/.

**Comment by jorrit** [comment]
It's just the example. The downside is that the examples are not excluded from the NPM package.

**Comment by apepper** [comment]
I know, that this is just the example. But I do see about the same size increase in a production app, that tried to use the newer `react-images` version. But since it adds another 100 kb payload we are sticking to `0.5.14` for now.

**Comment by jorrit** [comment]
Ah, that is awful. It seems that it is hard to import a single spinner from react-spinners using rollup without using code like `const BounceLoader = require('react-spinners/dist/spinners/BounceLoader').default;` instead of an ES6 import.

**Comment by neptunian** [comment]
Perhaps there is a way to remove react-spinners as a dependency and use it in your own app, so its only in the examples page.  Then at some point we should separate out the demos and have a simpler example in the build and the more advanced/detailed ones on the github site.

**Comment by jossmac** [comment]
Whoa, that's massive! Though shouldn't be a problem for too much longer.

@apepper @jorrit please see #199 -- i've rewritten the lib to allow consumers the ability to implement their own components. e.g. a custom view with spinner for loading

**Comment by mkalygin** [comment]
@jossmac @neptunian I think it's possible. Actually it already supports custom spinners. So we can safely remove the `react-spinners` dependency and provide a better documentation on how to add a basic custom spinner in examples. What do you think? I'll be able to implement this.

**Comment by neptunian** [comment]
Not sure when v1 is going to be ready so maybe best to take care of it now.  I'm okay with it being removed and only existing as documentation.  Ideally i'd like to have the website separated and this included, but for now, perhaps its best to keep it light.

**Comment by mkalygin** [comment]
@neptunian sounds good, I'll be able to solve it this weekend.

**Comment by mkalygin** [comment]
@apepper @jorrit @neptunian 

I've remove `react-spinners` dependency and implemented default spinner. You can also implement your own custom spinner, see examples. 😃

**Comment by apepper** [comment]
Thanks to everyone involved fixing this! 👏
