### ISSUE TITLE
The "srcSet" prop is inconsistent

### ISSUE THREAD

**Issue by kripod** [jossmac/react-images#203]
While preloading images, the `srcSet` prop [is being treated as a single string](https://github.com/jossmac/react-images/blob/cc2634f4c96ae2fbda0bb9f3e1f1d323a61d8d4b/src/Lightbox.js#L110-L112), but when rendering, [it is treated as an array of strings](https://github.com/jossmac/react-images/blob/cc2634f4c96ae2fbda0bb9f3e1f1d323a61d8d4b/src/Lightbox.js#L248-L256).

I think it would be better to use single strings instead of arrays to follow the standard notation of `srcSet`s, but in order not to break backwards compatibility, dynamic type checking should be used.

**Comment by kripod** [comment]
@jossmac I think this should not be closed yet, because single strings still cannot be used instead of string arrays for `srcSet`.

**Comment by neptunian** [comment]
this probably should not have been merged, as this merge was pending and would have resolved the issue https://github.com/jossmac/react-images/pull/175
