### ISSUE TITLE
Rotating Images

### ISSUE THREAD

**Issue by efeconirulez** [jossmac/react-images#205]
Two tiny rotate buttons near the close button (x) that handles the 90 degrees rotating left and right would be nice.

So users will be able to rotate the image to its correct direction. Ex:

![image](https://user-images.githubusercontent.com/12911212/35665991-490ae29a-0739-11e8-83a4-8ac6990c2a84.png)

**Comment by jossmac** [comment]
Sweet, a McFlurry!

Checkout the `customControls` property -- I think it's what you're looking for 😉
