### ISSUE TITLE
If `isOpen` is set as `true` from the start, the images don't get loaded, only the spinner gets displayed.

### ISSUE THREAD

**Issue by veronicaPop** [jossmac/react-images#206]
Version: "react-images": "^0.5.16",

**Steps to reproduce the behavior:**
Set `isOpen` as `true` from the start.

`<Lightbox
          images={ images }
          onClose={ onCloseRequest }
          onClickPrev={ this.gotoPrevious }
          onClickNext={ this.gotoNext }
          currentImage={ currentImage }
          isOpen={ true }
       />`

**Expected behavior:**
The lightbox is open after page load, with the first image displayed.

**Actual behavior:**
The lightbox is open after page load, but the images don't get loaded, only the spinner gets displayed.
No error is displayed in the console.

**Comment by neptunian** [comment]
@mkalygin i think this was introduced with your changes.  the error does not occur before 0.5.15.

**Comment by vladluca** [comment]
I encounter exactly the same problem, if ``isOpen`` is set to ``true`` from the beginning, the images does not load.

**Comment by mkalygin** [comment]
@neptunian yep, I'll take a look this weekend. 👍

**Comment by veronicaPop** [comment]
Hey there! 
Are there any updates on this? @mkalygin, did you get a chance to take a look?

**Comment by mkalygin** [comment]
@veronicaPop @neptunian 

I've fixed this issue in #207. This was a dumb error with type casting in JavaScript. 😄
