### ISSUE TITLE
CustomComponents to left & right

### ISSUE THREAD

**Issue by santiph** [jossmac/react-images#213]
I need the ability to display image metadata when the lightbox is opened to its left.
Fields like File name, Description, Upload on, file size and dimensions, which will result in very bad UX if those are shown in the top header of the image.

Any suggestion how to achieve this?

**Comment by jossmac** [comment]
Hi @santiph,

I'm afraid this isn't possible in v0.x -- though I'm working hard to ship v1 (#199 / #212 ) which would allow you to replace the `<View />` with your custom component! I'll make sure I add an example that covers this use in the docs.

In the meantime, please checkout the [developer preview](http://bit.ly/react-images-v1).

Best,
Joss

* * *

Closing for now, please comment if you need this issue re-opened.
