### ISSUE TITLE
Remove Image - Feature

### ISSUE THREAD

**Issue by Olivr3** [jossmac/react-images#214]
![screenshot from 2018-02-18 14-35-12](https://user-images.githubusercontent.com/20702895/36353031-f9ec20ec-14b8-11e8-9cd1-6df65f85f039.png)
**Steps to reproduce the behavior:**

**None**

**Expected behavior:**

The user can remove an image by clicking on the remove icon below the image.

**Actual behavior:**

There is no way to pass an action to `photos` obj in order to remove an image.

**Comment by jossmac** [comment]
Hi @Olivr3,

Are you aware of the `customControls` property? I think that might help.

I'm working hard to ship v1 (#199 / #212 ) which would allow you to replace the `<View />` with your custom component!

In the meantime, please checkout the [developer preview](http://bit.ly/react-images-v1).

Best,
Joss

* * *

Closing for now, please comment if you need this issue re-opened.
