### ISSUE TITLE
Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by lkazberova** [jossmac/react-images#216]
**Steps to reproduce the behavior:**
Set images & isOpen=true in one step. Please take a look at this https://codesandbox.io/s/k04jp5y447
**Expected behavior:**
Galllery is open
**Actual behavior:**
Gallery crash with error "Cannot read property 'complete' of undefined"

**Why:**
In this code we call preloadImage https://github.com/jossmac/react-images/blob/master/src/Lightbox.js#L89, but in preloadImage method we try to access "old" state of this.props.images https://github.com/jossmac/react-images/blob/master/src/Lightbox.js#L112

**Comment by rimatla** [comment]
Any update? Same boat here.

**Comment by DsAco** [comment]
0.5.17 not working either

**Comment by mushkab** [comment]
plus one

**Comment by arielgefen** [comment]
+1

**Comment by thg303** [comment]
is this repo alive??

**Comment by lkazberova** [comment]
If someone would like to get the react-images without this error please free to use 
```json
"react-images": "git://github.com/lkazberova/react-images.git#libs",
```
 in your package.json, because we don't know when an author of this repo will accept the pull-request.

**Comment by corydeppen** [comment]
@jossmac Understanding v1 is around the corner, is there anything specific that prevents this PR from being merged and released?

**Comment by LukeLin** [comment]
The error happens when you set images props as empty array, my fix way is:
`
this.state = {
      // This is important
      lightboxImages: [{
        src: ''
      }],
      lightboxIsOpen: false,
      currentImage: 0
    }
`
