### ISSUE TITLE
body element get padding-right: 596px; on mobile Android device

### ISSUE THREAD

**Issue by michalica** [jossmac/react-images#221]
**Steps to reproduce the behavior:**
create-react-app based project, using Redux for state management
**Expected behavior:**
after setting isOpen to true, body element should get pading-right: 0px
**Actual behavior:**
after setting isOpen to true, body element get pading-right: 596px (only on Android Device, Chrome Browser)

**Comment by neptunian** [comment]
i think this is something within your app as im not able to reproduce.
