### ISSUE TITLE
Portrait images

### ISSUE THREAD

**Issue by Sin-** [jossmac/react-images#222]
I want to display some photos with react-images but all my portrait images are displayed as landscape images (rotated by 90°). I opened them with different image software to make sure that they were really portrait and that the OS wasn't tricking me with the EXIF data.
These photos ARE portrait but yet here is what I get:

<img width="1317" alt="capture d ecran 2018-04-24 a 13 36 16" src="https://user-images.githubusercontent.com/11181821/39184744-eef3fc0c-47c4-11e8-8185-ba82695acb15.png">

Can anyone help? Thanks!

**Comment by neptunian** [comment]
if you open the image in a browser you will see they are probably not portrait as the Lightbox does not change your image.

**Comment by Sin-** [comment]
If I open the file directly in my browser, the photo appears in portrait.
I checked a thousand times and I can literally see that the thumbnail of the file is in portrait when I hover the image URL in chrome debugger.
Still the lightbox displays it in landscape

**Comment by neptunian** [comment]
If you want to point out to me what in the Lightbox code is causing this, please do, otherwise I imagine it must be something within your environment.

**Comment by jorrit** [comment]
This is probably an issue with EXIF rotation. It's a mess.
