### ISSUE TITLE
Uncaught TypeError: Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by pawlowskim** [jossmac/react-images#226]
**Steps to reproduce the behavior:**
Bascially I have passed array with images and isOpen flag.

**Expected behavior:**
Lightbox doesn't crash the application
**Actual behavior:**
"Null pointer exception"

There is some code in Lightbox.js:
```
// preload current image
if (this.props.currentImage !== nextProps.currentImage || !this.props.isOpen && nextProps.isOpen) {
    var img = this.preloadImage(nextProps.currentImage, this.handleImageLoaded);
				this.setState({ imageLoaded: img.complete });
			}
```

and I check "preloadImage" method and saw this:
```
var data = this.props.images[idx];

if (!data) return;

var img = new Image();
var sourceSet = normalizeSourceSet(data);

// TODO: add error handling for missing images
img.onerror = onload;
img.onload = onload;
img.src = data.src;

if (sourceSet) img.srcset = sourceSet;

return img;
```

It's obvious bug since preloadImage method can return nothing, and in the first snippet you always use img.complete no matter if img is undefined or not.

**Comment by neptunian** [comment]
see #216
