### ISSUE TITLE
react transition group: Migrate to v2

### ISSUE THREAD

**Issue by GiancarlosIO** [jossmac/react-images#227]
I have a project with a lot of components using react-transition@v2 and when I try to build my app react-images show a error because the CSSTransitionGroup was removed in v2.
Any plans to migrate to v2? :thinking:

**Comment by filipecosta01** [comment]
I did it already, just need to wait the guys to promote to production and release.

https://github.com/jossmac/react-images/pull/238

**Comment by GiancarlosIO** [comment]
@filipecosta01 thank you!
