### ISSUE TITLE
How to enable goToPrev and goToNext?

### ISSUE THREAD

**Issue by jiehan1029** [jossmac/react-images#239]
I'm fairly new to this and just followed the demo code, but very confused on how to implement the goToPrev and goToNext. Though I can input a set of image src, I cannot navigate in the lightbox. Am I supposed to write the prev and next function myself? It would be very convenient if the prev and next functionality can be there automatically based on the image src array the user input...Anyone give me a hint? Will appreciate it!

**Comment by chuckconway** [comment]
This took a bit to figure this out. This really should be in the documentation... maybe it is there, but I missed it. 

To change the image, you have to set/change currentImage prop on the Lightbox component.

Here is what my methods look like:

          <Lightbox
              images={this.state.items}
              isOpen={this.state.isOpen}
              currentImage={this.state.activeIndex}
              onClickPrev={this.previous}
              onClickNext={this.next}
              onClose={this.props.onClose}
          />

Next
```
  next = () => {
    const nextIndex = this.state.activeIndex === this.state.items.length - 1 ? 0 : this.state.activeIndex + 1;

      this.setState({
          ...this.state,
          activeIndex: nextIndex
      });
  };
```

Previous
```
  previous = () => {
    const nextIndex = this.state.activeIndex === 0 ? this.state.items.length - 1 : this.state.activeIndex - 1;

      this.setState({
          ...this.state,
          activeIndex: nextIndex
      });
  };
```

**Comment by jiehan1029** [comment]
@chuckconway Thank you Chuck!! This works great. Yep because those methods appear in the example code without any explanation so I was assuming that it was built-in, but actually not.... would be nice if there can add more details in documentation.

**Comment by jossmac** [comment]
@jiehan1029 I recommend looking at the example app, especially [Gallery.js](https://github.com/jossmac/react-images/blob/master/examples/src/components/Gallery.js) -- the salient methods:

```jsx
gotoPrevious () {
  this.setState(state => ({
    activeIndex: state.activeIndex - 1,
  }));
}
gotoNext () {
  this.setState(state => ({
    activeIndex: state.activeIndex + 1,
  }));
}
gotoImage (index) {
  this.setState({
    activeIndex: index,
  });
}
```

I recommend using a [function to set state](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous) in this case so you always have the latest value.

* * *

@chuckconway FYI react-images internally handles disabling the `next/prev` methods when applicable, so you don't have to check that 🙂 

Also, it's worth mentioning that React merges the object you provide into the current state, so you don't have to when calling `setState`. More about that [in the docs](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-are-merged).

**Comment by chuckconway** [comment]
@jossmac Thanks for the pointers, I appreciate it.  I'm somewhat new to React and I'm still figuring out the nuances.

**Comment by jossmac** [comment]
BTW I'm working on [Version 1](http://bit.ly/react-images-v1) where I hope to improve documentation and the developer experience.
