### ISSUE TITLE
backdropClosesModal has no effect

### ISSUE THREAD

**Issue by davidspiess** [jossmac/react-images#24]
Clicking the backdrop does not close the lightbox, neither if i set `backdropClosesModal` explicit when initializing it.
I tested it with Chrome and Firefox.

**Comment by RobinTail** [comment]
+1. The same behavior is on the Demo website.

**Comment by jossmac** [comment]
Thanks for catching this. Please update to v0.3.2

**Comment by jossmac** [comment]
Sorry for the slow response btw, i've been on vacation

**Comment by davidspiess** [comment]
Awesome :+1: 
No worries, hope you had a great time!

One minor thing, i noticed after updating i had to set `backdropClosesModal` explicit to make it work.
The documentation points out it would default be `true`.

**Comment by jossmac** [comment]
Yeah, I've changed the default behaviour now that there's a nice close button/icon:
- backdropClosesModal `false`
- showCloseButton `true`
