### ISSUE TITLE
infinite/wrap option?

### ISSUE THREAD

**Issue by andyford** [jossmac/react-images#243]
Sorry if this is already answered elsewhere, but is there a way to make the navigation "wrap" so it returns to the beginning if you click "next" when on the last image; and it goes to the end when you click "previous" on the first image?

**Comment by yashamuru** [comment]
Hello , I think they are addressing this on the V1 (See #195 #199).

**Comment by jossmac** [comment]
@andyford the state of `currentImage` is handled by the consumer, you just need to account for it in your `next/prev` methods. Something like:

```jsx
next = () => {
  this.setState(state => {
    const currentImage = state.currentImage === state.items.length - 1
      ? 0
      : this.state.currentImage + 1;

    return { currentImage };
  });
};
```

**Comment by anisval** [comment]
@jossmac that is a cool idea. The only problem, I think, is that the `next` method is not called because of the condition inside `gotoNext`:

`if (!imageLoaded || currentImage === images.length - 1) return;`

or am I missing something?
