### ISSUE TITLE
Problem with babel

### ISSUE THREAD

**Issue by tomhalley** [jossmac/react-images#245]
I have babel setup inside a create-react-app app I started about a year ago. I had `    "react-images": "^0.5.17",` in my package.json, so when you released the new 0.5.18 a couple of hours ago, I pulled it down, at which point babel started failing to build as it was including the raw ES6 of your library instead of transpiling it.

Would give more information if I could but don't know what would be helpful?

**Comment by jasonnutter** [comment]
We are getting the following error now in our frontend app that uses `react-images`:

```
/node_modules/react-images/lib/Lightbox.js:9
import PropTypes from 'prop-types';
^^^^^^

SyntaxError: Unexpected token import
```

**Comment by neptunian** [comment]
Sorry, please see latest release and let me know.

**Comment by tomhalley** [comment]
@jasonnutter Yes this is exactly what I saw, because it's not compiled the react-images library properly. I had to go back to 0.5.16 to get around the issue.

**Comment by neptunian** [comment]
@tomhalley it should be okay now.

**Comment by billnbell** [comment]
This brought down our build system for several hrs today. Can you implement a basic test to make sure lib/* is transpiled going forward?

**Comment by neptunian** [comment]
@billnbell in v1 but this version will probably not be updated much anymore.  i definitely wont be messing with the build like i did :)
