### ISSUE TITLE
[v1] Server-side rendering is not working

### ISSUE THREAD

**Issue by kripod** [jossmac/react-images#247]
**Steps to reproduce the behavior:** Import the `ModalGateway` component from `react-images@1.0.1-alpha.1` and then try running `gatsby build` (or any other server-side renderer) on a project. Reproduction repo: [simonyiszk/schdesign-web@441597e](https://github.com/simonyiszk/schdesign-web/commit/441597eef8d7aeadf332b9126c7ff84ecd44a552)

**Cause:** https://github.com/jossmac/react-images/blob/86894619fbadc3d63160fed46fe3de4242d3668e/src/components/Modal/Gateway.js#L15

There should be a `typeof window !== 'undefined'` check to avoid accessing `document` outside of browser environments.

**Comment by mustafa-hanif** [comment]
This dude has solved it
[](https://github.com/jossmac/react-images/issues/199#issuecomment-443604782)
