### ISSUE TITLE
Is it possible to pass an Image component instead of image src?

### ISSUE THREAD

**Issue by daydream05** [jossmac/react-images#249]
Hi, I use [Gatsby](https://github.com/gatsbyjs/gatsby) and it has a nice [Image component](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image) that basically does lazy loading and other nice optimizations. Is it possible if I can just pass an Img component instead of passing an object? Thanks

**Comment by jossmac** [comment]
That's the intention behind the [v1 rebuild](https://github.com/jossmac/react-images/pull/212); all components are replaceable.
