### ISSUE TITLE
When LightBox component opens it puts style on body 

### ISSUE THREAD

**Issue by Apoorv-Mittal** [jossmac/react-images#250]
**Steps to reproduce the behavior:**
Open Lightbox component

**Expected behavior:**
`<body>`

**Actual behavior:**
`<body style="box-sizing: border-box; overflow: hidden; position: relative; height: 3533px; padding-right: 15px;" > `

How can I prevent this from happening?

**Comment by danielmhanover** [comment]
+1

**Comment by jossmac** [comment]
Pass `false` to the `preventScroll` property. You can view all the [props in the README.md](https://github.com/jossmac/react-images#options).
