### ISSUE TITLE
Escape keydown handled by modal instead of lightbox

### ISSUE THREAD

**Issue by rkkautsar** [jossmac/react-images#251]
**Steps to reproduce the behavior:**
Use `react-images` inside a `react-modal`

**Expected behavior:**
<kbd>ESC</kbd> button close only the lightbox

**Actual behavior:**
<kbd>ESC</kbd> button close the modal, but the lightbox close event is not fired. Here's a simple reproduction: https://codesandbox.io/s/rrxq8w417q

It seems that the keydown event is handled by the modal because the modal is still in focus (instead of the lightbox). If I click on the lightbox first before pressing <kbd>ESC</kbd>, it works as expected.

**Comment by neptunian** [comment]
fixed in v1
