### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by hesedel** [jossmac/react-images#253]
Is it possible to replace all the other icons (prev, next, close) and not just the spinner?

**Comment by harby** [comment]
What I did instead was, I turned off the close button and the next / prev arrows and I passed custom components using the `customControls` property. Hope it helps.

**Comment by SalahEddineBC** [comment]
@harby  how you did turn off arrows button please?

**Comment by SalahEddineBC** [comment]
@harby  how you did turn off arrows button please?

**Comment by SalahEddineBC** [comment]
@harby  how you did turn off arrows button please?

**Comment by neptunian** [comment]
Please see the new version for adding custom components.
