### ISSUE TITLE
Lightbox with comment or some element for more view data

### ISSUE THREAD

**Issue by M-Husein** [jossmac/react-images#254]
Hi,

thanks for share you work, nice work ;)
Btw I think it would be better if there was an option to add elements or components to display data such as comments etc.

I mean like Facebook Lightbox:

![image](https://user-images.githubusercontent.com/19644272/44622544-c1aab480-a8e4-11e8-932b-a3df3d032297.png)

I hope this will be available. Thank you very much. ;)

**Comment by jdsandifer** [comment]
I'm interested in adding an option to display additional content below images. This could be longer text descriptions, custom React components, links, etc.

I think this would also allow for comments like M-Husein is requesting.

I foresee it being implemented very much like custom controls are currently set up. (In fact, I'm using the custom controls option to display a custom React component with some links right now. I'd like to also add some larger content below the images where I think it would look better.)

Is this something that is in line with your vision for the project?

I'd be willing to add the feature myself via a PR.

**Comment by neptunian** [comment]
Please see v1 for adding custom components.

**Comment by sickerin** [comment]
Anyone has demos or examples of this?

**Comment by francisrod01** [comment]
Hi @sickerin, I'm going to post it in few days, because I'm pretty interested in this repo. :) :+1:
