### ISSUE TITLE
Disappearing scrollbar on lightbox show

### ISSUE THREAD

**Issue by alexey-broadcast** [jossmac/react-images#26]
If a page has scrollbar ![image](https://cloud.githubusercontent.com/assets/3949614/13009814/938b78dc-d1af-11e5-9f42-be8786dc9148.png)
it disappears on lightbox show 
![image](https://cloud.githubusercontent.com/assets/3949614/13009842/b1b2f18c-d1af-11e5-9166-3cdf4287c150.png)

Also, in IE, when we close lightbox - scrollbar doesn't appear

**Comment by alexey-broadcast** [comment]
upd: when lightbox is shown, body gets style "overflow: hidden". Is it necessary?

**Comment by neptunian** [comment]
@alexey-broadcast  This is typical behavior for a lightbox.  The focus is the photo which will fit in the viewport so there is no need to scroll.

**Comment by alexey-broadcast** [comment]
Ok, but it makes centered content "jumping" horizontally when lightbox toggles, and 
> in IE, when we close lightbox - scrollbar doesn't appear

**Comment by primozs** [comment]
how is this fixed?

**Comment by davwheat** [comment]
Because this was an issue 5 years ago, and became not an issue. If it's an issue now, feel free to open another issue, but noone is maintaining this library anymore.
