### ISSUE TITLE
Would like to add Russian translation 

### ISSUE THREAD

**Issue by bologer** [jossmac/react-images#260]
Thank you for your library. 

Just want to help with Russian translation. 

Here it is: 

```js
Lightbox.defaultProps = {
	closeButtonTitle: 'Закрыть (Esc)',
	imageCountSeparator: ' из ',
	leftArrowTitle: 'Предыдущая (левая стрелка)',
	rightArrowTitle: 'Следующая (правая стрелка)',
	...
};
```

Would be cool if you could have prop `language` and use one of the predefined, if there is such. 

Thanks.

**Comment by GYTO** [comment]
`react-image` already has a deafultProps which can be overwritten with `rightArrowTitle` or etc. If you want to have translation and support of internationalization you can use [react-i18next](https://react.i18next.com/getting-started)
