### ISSUE TITLE
onClose doesn't return any event

### ISSUE THREAD

**Issue by hypervillain** [jossmac/react-images#261]
Hey guys,

I'm using a Lightbox component inside a Drawer that also closes on escape key down.
Unfortunately, Lightbox's `onClose` doesn't return any event, and prevents me from capturing the event and treat it appropriately. I know I could wrap the Lightbox inside another KeyListener but `onClose` returning its event would be much cleaner 🙌

**Expected behavior:**

```
<Lightbox
     isOpen={this.state.lightboxIsOpen}
    onClose={(e) => {
         console.log(e); // => Event
     }}
/>
```

Thanks!

**Comment by paulmichaelxd** [comment]
Hey @THook !

I don't haven't made any PRs to react-images or anything, but I have been using it for a while & I do something similar in one of my projects.

Do you really need the event for onClose to achieve this behavior?
You probably have a parent component that holds the state for your drawer being open & the Lightbox being open. Why not just have the onClose callback update both states?

i.e.
```
state = {
  drawerIsOpen: true,
  lightboxIsOpen: true,
};
...

<Lightbox
  isOpen={this.state.lightboxIsOpen}
  onClose={() => this.setState({
    drawerIsOpen: false,
    lightboxIsOpen: false,
  })
/>
```
