### ISSUE TITLE
"close" button is not showing in google chrome's landscape resolution on mobile devices

### ISSUE THREAD

**Issue by Saurabh-ASCI** [jossmac/react-images#262]
Hello Guys,

I am using lightbox component to preview images. It is great. 

But I have facing issue while viewing images in android chrome browser - landscape view, "close" button gets hidden under the chrome's url header.
Please refer this [screenshot](https://user-images.githubusercontent.com/40362099/47269237-8d681300-d578-11e8-8240-03dca776a536.jpeg)

Please let me know if there is any way to handle this.

Thank you.

**Comment by neptunian** [comment]
Please see the new version.
