### ISSUE TITLE
After close, gallery items lost the style

### ISSUE THREAD

**Issue by francisrod01** [jossmac/react-images#266]
Server-side rendering problem about this example: https://github.com/Khan/aphrodite/issues/350

**Steps to reproduce the behavior:**

`AFTER` close the Lightbox popup, the `<a>` links lost the style.

https://github.com/jossmac/react-images/blob/master/examples/src/components/Gallery.js#L64

**Expected behavior:**

![image](https://user-images.githubusercontent.com/4691768/49047556-8efbab00-f1b6-11e8-97e3-3bbd2822745c.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/4691768/49047599-b81c3b80-f1b6-11e8-96cd-b41c77beca66.png)

Envs:

* react: 16.6.3
* react-images: 0.5.19
* npm: 6.4.1
* node: v8.11.2

**Comment by janklimo** [comment]
@francisrod01 I was seeing a similar problem. If it's not too complex, I'd recommend upgrading to `react-images@next` which doesn't have that issue.

**Comment by francisrod01** [comment]
I see it. I solved it removing the css style from the link `<a>` component, but I'd like to see this full example improved later.
