### ISSUE TITLE
No fade in / out animation

### ISSUE THREAD

**Issue by freznosmooth** [jossmac/react-images#273]
**Steps to reproduce the behavior:**
Followed getting started tutorial with basic example of Lightbox

**Expected behavior:**
On open -> Lightbox fades in
On close -> Lightbox fades out

**Actual behavior:**
Lightbox opens and closes instantly with no animation.

On inspection it looks like the styles for animation are being added above the component
```
.fade-enter { opacity: 0.01; }
.fade-enter.fade-enter-active { opacity: 1; transition: opacity 200ms; }
.fade-leave { opacity: 1; }
.fade-leave.fade-leave-active { opacity: 0.01; transition: opacity 200ms; }
```
But the classes `.fade-enter` etc never get added to the component on mount / unMount.

**Comment by neptunian** [comment]
Please see the new version which has animation.
