### ISSUE TITLE
Multiple lightbox

### ISSUE THREAD

**Issue by lpluispacheco** [jossmac/react-images#279]
Hi, is possible have more than just 1 lightbox per page?

I have 3 cards and I need that every card when the user clicks on it trigger differents lightboxes with their own images.

Thanks

**Comment by choubeyaakash77** [comment]
Hi @lpluispacheco,

I recently implemented just that. But in my case, I had each card as a component and I used lightbox within that element. That's one way to go.

Lightbox component requires images props. You can have a state and feed it to the lightbox. Update the state with an array of objects , like `[{src:"image-url1"},{src:"image-url2"},{src:"image-url3"}]` based on which card you selected.

Hope it helps.

**Comment by choubeyaakash77** [comment]
Hi @lpluispacheco,

I recently implemented just that. But in my case, I had each card as a component and I used lightbox within that element. That's one way to go.

Lightbox component requires images props. You can have a state and feed it to the lightbox. Update the state with an array of objects , like `[{src:"image-url1"},{src:"image-url2"},{src:"image-url3"}]` based on which card you selected.

Hope it helps.

**Comment by neptunian** [comment]
Yes, you need to implement it in your own app by passing a unique set of images to it and keeping track of each one.
