### ISSUE TITLE
autosize height on mobile cuts off majority of image

### ISSUE THREAD

**Issue by dadamssg** [jossmac/react-images#282]
**Steps to reproduce the behavior:**
Open the lion example, open chrome developer tools, turn on the device toolbar and select iPhoneX.

It appears that the `react-images__frame` div  is having it's height set automatically, but strangely on smaller screens

**Expected behavior:**
If you manually uncheck the height it seems to behave properly. 
![image](https://user-images.githubusercontent.com/881986/59277121-34431180-8c25-11e9-9e6e-38fc9830249a.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/881986/59276628-4ec8bb00-8c24-11e9-9406-2d60f945cbe2.png)

**Comment by tom-james-watson** [comment]
This is what it looks like when viewing on both Firefox and Chrome on an actual Android as well.

**Comment by iammatthias** [comment]
Also happening on iOS 12 and the iOS 13 beta.

**Comment by neptunian** [comment]
```

            <Carousel
                components={{ FooterCaption }}
                currentIndex={selectedIndex}
                formatters={{ getAltText }}
                frameProps={{ autoSize: 'height' }}
                views={images}
              />
```
Are you padding autoSize: 'height' to Carousel?  Try removing it and I think that will fix it.  Probably a bug in react-view-pager

**Comment by tom-james-watson** [comment]
Why has this been closed? The default example on the homepage is completely broken on mobile.
