### ISSUE TITLE
Deprecate v0.6.7 on npm

### ISSUE THREAD

**Issue by rarkins** [jossmac/react-images#283]
Please run `npm deprecate react-images@0.6.7 "invalid release"` so that people running 0.5.x are not prompted to upgrade to 0.6.7.

Cc @Scritik

**Comment by neptunian** [comment]
Thanks.  But where are you getting 0.6.7?

**Comment by rarkins** [comment]
It is technically a valid upgrade from 0.5.19. Here's the shortest example of where you could end up installing 0.6.7 too:

```
{
  "name": "test1",
  "version": "1.0.0",
  "dependencies": {
    "react-images": "0.*"
  }
}
```

**Comment by Scritik** [comment]
@neptunian Any news for the deprecation?

**Comment by neptunian** [comment]
I ran it.  Let me know if that worked.

**Comment by Scritik** [comment]
All good, thx!
