### ISSUE TITLE
Where is changelog or migration guide for new major version?

### ISSUE THREAD

**Issue by Rogach** [jossmac/react-images#288]
It seems that between 0.5.19 and 1.0.0 a breaking change happened (`images` prop got renamed to `views`), but there is no migration guide or Changelog.md to be found on the main page or in the repo.

**Comment by neptunian** [comment]
Yes, that's why it was pushed to 1. https://semver.org/
The new version is totally different.  The best way to upgrade is read the docs and follow the examples.

**Comment by Rogach** [comment]
Yes, I know semver. However, when I saw no migration notice I assumed that this was just a `1.x` "stable" release and there are no breaking changes (because otherwise usually projects put up a migration notice). Can we a least add something like `If you were using 0.x version: The new version is totally different. The best way to upgrade is read the docs and follow the examples` into the readme to avoid confusing users? I would be happy to provide a PR if needed.

**Comment by neptunian** [comment]
@Rogach I see. Would very much welcome a PR.

**Comment by Rogach** [comment]
Done: #290

**Comment by qlerebours** [comment]
For those searching for the previous documentation: https://www.npmjs.com/package/react-images/v/0.5.19
