### ISSUE TITLE
Scroll in one line?

### ISSUE THREAD

**Issue by MarinaaaniraM** [jossmac/react-images#29]
Can I scroll small images in one line, as carousel? How can I do it?

I have structure:
```
<div>
<a>
<a>
...
<a>
</div>
```
this _div_ generated when rendered _Lightbox_, and I can't assign some style for it (for example, _display: table-cell_)... But I want all small images inline with scroll...

**Comment by jossmac** [comment]
@MarinaaaniraM the main idea of this package is to be simple and lightweight, that's why each image is loaded on request. Sorry this is not your desired behaviour.

Theming is definitely something I'd like to add in the future.
