### ISSUE TITLE
closeOnBackdropClick={true} not working

### ISSUE THREAD

**Issue by liuweiGL** [jossmac/react-images#302]
```
!event.target.classList.contains(className('view')

// should be

event.target.classList.contains(className('view')
```
https://github.com/jossmac/react-images/blob/6a17d97a311aea2f40667af30219e545ef789ce3/src/components/Modal/Modal.js#L107

**Comment by spaghettiguru** [comment]
any progress with this?

**Comment by liuweiGL** [comment]
> any progress with this?

Not yet.

**Comment by rockneverdies55** [comment]
@jossmac - can you please provide some feedback on this or merge the fixing PR?
