### ISSUE TITLE
IE11 modal carousel too wide

### ISSUE THREAD

**Issue by Colin-Suckow** [jossmac/react-images#304]
Using a standard modal with carousel containing multiple images. In my case more than 3 but it depends on screen resolution

When displaying a carousel containing multiple images in IE11, the carousel component extends outside the bounds of the screen, causing images and arrow controls to be cutoff. I did notice that the div with className react-images__dialog is not abiding by the flex-shrink property, but does in chrome in firefox. This may or may not be related.

[Screenshot of issue in IE11 on Windows 10](https://i.imgur.com/AED1B9z.png)

**Comment by jossmac** [comment]
Resolved by #329
