### ISSUE TITLE
Implement Unsplash Images

### ISSUE THREAD

**Issue by jossmac** [jossmac/react-images#31]
Get local images out of the repo: https://unsplash.com/documentation

**Comment by GregoryPotdevin** [comment]
It looks like Unsplash allows hotlinking

> Unlike most APIs, we prefer for the image URLs returned by the API to be directly used or embedded in your applications (generally referred to as hotlinking). By using our CDN and embedding the photo URLs in your application, we can better track photo views and pass those stats on to the photographer, providing them with context for how popular their photo is and how it’s being used.

So you could just pick 10-15 photo ids and generate the urls with the correct sizes : 
Thumnbail : https://images.unsplash.com/photo-1457200246108-d9d4abc27953?dpr=2&auto=format&crop=entropy&fit=crop&w=120&h=120
Large size : https://images.unsplash.com/photo-1457200246108-d9d4abc27953?dpr=2&auto=format&w=1000

(thumbnails should have width and height set, as well as `fit=crop` if you want to crop. For full size images, just set the max width and remove the crop.

If you want I can do a quick PR with unsplash images to lighten the repo.

**Comment by jossmac** [comment]
@GregoryPotdevin yes please! Let's stick with the current theme and use the [Spirit Animals Collection](https://unsplash.com/collections/158825/spirit-animals)

**Comment by GregoryPotdevin** [comment]
Perfect, thanks :)

**Comment by GregoryPotdevin** [comment]
Online demo : http://tamago.fr/react-images-unsplash/

Selected images :
![image](https://cloud.githubusercontent.com/assets/1522455/17810888/119c2f14-6620-11e6-9715-537f814ae944.png)
