### ISSUE TITLE
Support for image srcset and sizes

### ISSUE THREAD

**Issue by TuxGit** [jossmac/react-images#311]
Good day

Need support for responsive images, attributes **srcset** and **sizes**.

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

Example:
```
    srcSet: [
      "https://source.unsplash.com/2ShvY8Lf6l0/500x375 500w",
      "https://source.unsplash.com/2ShvY8Lf6l0/1024x768 1024w"
    ],
    sizes: ["(min-width: 480px) 500w,(min-width: 1024px) 1024w"]
```

**Comment by mbrandau** [comment]
You can do that on your own by overwriting the `View` component.
https://jossmac.github.io/react-images/#/components

```jsx
<Carousel
  // ...
  components={{
    FooterCount: ({ currentIndex, views }) =>
      `${currentIndex + 1} von ${views.length}`,
    View: ({ data }) => {
      // Or render your own image.
      return <GatsbyImage fluid={data.fluid}/>
    },
  }}
// ...
```

**Comment by jossmac** [comment]
@TuxGit for some context, I tried to support a bunch of variants in the initial implementation, but you can't know everyones needs or constraints. Trying to solve for everything creates a horrible API.

In `v1`, as mentioned by @mbrandau, you can just replace the component that you need to.

**Comment by jossmac** [comment]
I will add that it's recommended to create the `components` object outside of render.

**Comment by onadeem1** [comment]
is srcSet no longer supported?
