### ISSUE TITLE
react-scrolllock causing warning with React 16

### ISSUE THREAD

**Issue by mikestecker** [jossmac/react-images#314]
**Steps to reproduce the behavior:**
With `"react-images": "^1.0.0"`, I get the following error:
`react-scrolllock@1.0.9 requires a peer of react@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.`

**Expected behavior:**
Would like to see the peer dependency updated for React 16 compatibility.

In searching through issues here, it seems like this was quite possibly [fixed at](https://github.com/jossmac/react-images/pull/190) [some point](https://github.com/jossmac/react-images/pull/196)  (unless I'm not following everything correctly) but it doesn't appear in `1.0.0`

**Comment by davwheat** [comment]
Should be fixed with the update to scrolllock v4 in #321
