### ISSUE TITLE
How can z-index of Modal component be changed ?

### ISSUE THREAD

**Issue by leonardo-sj** [jossmac/react-images#315]
**Steps to reproduce the behavior:**
https://codesandbox.io/s/react-photo-gallery-with-image-viewer-mbtp8

**Expected behavior:**
The Modal component should appears in front of Material UI AppBAr.

**Actual behavior:**
The Modal component is appearing behind the Material UI AppBAr.

The z-index of AppBar can be easily changed but it will affect the interaction with other components of Material UI.
The best solution is change the z-index of Modal. Can it be done ?

**Comment by mbrandau** [comment]
I just stumbled across the same problem a minute ago and solved it that way:
```jsx
<ModalGateway>
        {lightboxIsOpen && !isLoading ? (
          <Modal onClose={toggleLightbox} styles={{
            blanket: (base,state)=>({...base,zIndex:1100}),
            positioner: (base,state)=>({...base,zIndex:1110}),
            dialog: (base,state)=>({...base,zIndex:1120})
          }}>
            <Carousel
              currentIndex={selectedIndex}
              frameProps={{ autoSize: "height" }}
              views={images}
            />
        </Modal>
    ) : null}
</ModalGateway>
```
Check http://jossmac.github.io/react-images/#/styles for more information on styling.
