### ISSUE TITLE
Is it possible to pass to components prop a custom component as Header?

### ISSUE THREAD

**Issue by kboul** [jossmac/react-images#317]
Hi, 

Thank you very much for the useful plugin. I would like to ask whether is possible to pass a prop or a custom component that receives props as a Header

For instance suppose we want to pass a text as a header
```
const Header = ({ innerProps, isModal, text }) =>
    isModal && (
        <div {...innerProps}>
            {text}
        </div>
    );
```

or pass a component like a children element:
```
const Header = ({ innerProps, isModal, children }) =>
    isModal && (
        <div {...innerProps}>
            {children}
        </div>
    );
```

and then import it somehow in the components prop:
```
 <ModalGateway>
           {modalIsOpen && (
                  <Modal onClose={this.toggleModal}>
                         <Carousel
                                views={images}
                                components={{ Header }}
                            />
                  </Modal>
           )}
</ModalGateway>
```

Is it possible? 

Thank you in advance.

**Comment by SzymonNiemiec** [comment]
Hi, I figured out how to do this.
In components pass your custom prop as below:
`components={{
                Header: props => (
                  <CustomHeader {...props} yourCustomProp={yourCustomProp} />
                )
              }}`
and then in CustomHeader component: 

`
const CustomHeader = ({
  innerProps,
isModal,
  yourCustomProp
}) =>
  isModal ? (
    <div {...innerProps}>
{yourCustomProp}
    </div>
  ) : null;
`

**Comment by jossmac** [comment]
@SzymonNiemiec @kboul you can pass custom props to the carousel and access them from internal components.

```jsx
<Carousel yourCustomProp="goes here" />

// within header
const { carouselProps } = this.props;

console.log(carouselProps.yourCustomProp) // "goes here"
```

The reason for this is so that you aren't creating new components every the render cycle, which is what happens with the other approach.
