### ISSUE TITLE
HeaderClose & HeaderFullscreen buttons are not visible when passing Header to components prop

### ISSUE THREAD

**Issue by kboul** [jossmac/react-images#318]
**Steps to reproduce the behavior:**
Please see the following sandbox: https://codesandbox.io/s/carousel-using-react-images-tg3wy

**Expected behavior:**
To be able to see and use HeaderClose & HeaderFullscreen buttons when passing a Header to compoennts prop

**Actual behavior:**
There are not visible in the screen.
Also the string Header is 'lost' and not properly displayed

**Comment by jossmac** [comment]
@kboul when you replace the `Header` component you replace its children, so it makes sense that the close and fullscreen buttons aren't available.

You can import the defaults and compose them however you like:

```jsx
import { carouselComponents } from 'react-images'

const { HeaderClose, HeaderFullscreen } = carouselComponents
```
