### ISSUE TITLE
Image size in Carousel affects other images

### ISSUE THREAD

**Issue by sickerin** [jossmac/react-images#320]
**Steps to reproduce the behavior:**
- have different sized images in the Carousel.
- images I used.
259x194
265x190
1200x946

**Expected behavior:**
- the images in the carousel should not affect one another

**Actual behavior:**
- having a bigger image in the carousel hid the smaller image (it completely disappeared)
- if the biggest image was slightly smaller (maybe 500x300 instead of 1200x946), the smaller images would get cropped.

here's a gif of what happened
![ezgif-5-901ef0dec442](https://user-images.githubusercontent.com/12108084/65491850-72b5c100-dee2-11e9-9a6b-a14db62bddea.gif)

relevant code
`        <ModalGateway>
          {lightboxIsOpen ? (
            <Modal
              onClose={this.toggleLightbox}
              styles={{
                blanket: (base, state) => ({ ...base, zIndex: 1100 }),
                positioner: (base, state) => ({ ...base, zIndex: 1110 }),
                dialog: (base, state) => ({ ...base, zIndex: 1120 })
              }}
            >
              <Carousel
                currentIndex={selectedIndex}
                frameProps={{ autoSize: "height" }}
                views={images}
              />
            </Modal>
          ) : null}
        </ModalGateway>`

images used:
![download (11)](https://user-images.githubusercontent.com/12108084/65491607-f7540f80-dee1-11e9-9015-5786327aff73.jpeg)
![download (10)](https://user-images.githubusercontent.com/12108084/65491513-c1169000-dee1-11e9-919e-a1e5a1737292.jpeg)
![DY6qQ-CW0AAmRn_](https://user-images.githubusercontent.com/12108084/65491531-ca076180-dee1-11e9-9660-7bf192fc7429.jpg)

**Comment by djih** [comment]
@sickerin try changing to `frameProps={{ autoSize: "auto" }}`
