### ISSUE TITLE
Mobile pinch zoom?

### ISSUE THREAD

**Issue by sebastialonso** [jossmac/react-images#33]
This is a great library and it works sufficiently good for mobile.

I was wondering how hard would it be to implement pinch zoom to the images, or what are the steps I might take for the implementation of this.

Thanks!

**Comment by jossmac** [comment]
Hi!

Touch support would be awesome, though to be honest I hadn't given much thought to pinch-to-zoom. Was mainly considering swipe for next/prev via #15 

There's a few ports of [Hammer.js](http://hammerjs.github.io/) to React - I'd probably starter there

**Comment by sebastialonso** [comment]
Thank you.
