### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by coisnepe** [jossmac/react-images#331]
There are 24 open PRs, some of which could be very easily merged, and 28 issues. @jossmac seems to be pretty active on Github with other packages, yet is nowhere to be found on this repo. The last time he replied to an issue was in [February 2018](https://github.com/jossmac/react-images/issues/167#issuecomment-362198875) !
Why can't other core maintainers be added ? Or let's fork ?

**Comment by Migweld** [comment]
Indeed the last merge was back in June. Do we know if @jossmac has been contacted about adding more maintainers through methods other than on here?

I'd say if that is tried and we don't hear anything then fork and carry on ¯\_(ツ)_/¯

**Comment by davwheat** [comment]
I've forked this and pushed it to NPM.

I've also merged some PRs into the fork.

https://github.com/davwheat/react-images-maintained

**Comment by jossmac** [comment]
As mentioned, I'm not very active with this repo anymore. I still believe in Open Source, but got really burnt out. I have to prioritise my family.

Please raise your hand if you'd like to be a maintainer 👋 

Or, obviously just fork / take want you like from the lib.

**Comment by davwheat** [comment]
✋ I'd happily (try my best) to maintain it!

**Comment by jossmac** [comment]
@davwheat invitation sent. What's your username for npm?

**Comment by davwheat** [comment]
Thanks a bunch. Npm username is the exact same as on here.

**Comment by coisnepe** [comment]
@jossmac Thanks for stopping by :-) Family comes before everything else! Take care! 💪

**Comment by mhedengren** [comment]
Hey guys! A pinch to zoom feature for mobile devices would be very appreciated =)!

**Comment by davwheat** [comment]
I completely agree with you. Could you open up another issue as this one
has been closed and is unrelated?

Thanks!
