### ISSUE TITLE
No controls on mobile

### ISSUE THREAD

**Issue by deadline98** [jossmac/react-images#335]
**Steps to reproduce the behavior:**
- open the Carousel in a Modal on a mobile device.

**Expected behavior:**
Controls (next/prev) should be visible

**Actual behavior:**
Controls are not visble

I'm not quite sure if I'm missing anything in the docs, but it looks like the controls are hidden on mobile devices (also in the examples) and I can't seem to find any option to change that behavior. Is that intended? Can I change this somehow?

**Comment by deadline98** [comment]
I looked into the source code and found following code:

```javascript
export const Navigation = (props: NavProps) => {
  const { children, getStyles, isFullscreen, isModal } = props;
  return !isTouch() ? ( //this line causes this behavior.
    <Nav
      css={getStyles('navigation', props)}
      className={className('navigation', { isFullscreen, isModal })}
    >
      {children}
    </Nav>
  ) : null;
};
```

So it looks like it specifically doesn't render the image in touch devices. Any idea what's the reason for that? 

If this is a project decision, it should still give an option to overwrite that behavior and force the controls to be visible. 

I could open a PR if you agree on having a prop to overwrite that.

**Comment by davwheat** [comment]
Feel free to open a pull request. You should definitely have the option of
enabling this or not.

**Comment by deadline98** [comment]
I've opened a PR. Let me know if I need to add anything else.
