### ISSUE TITLE
Use uptodate version of react-images as hosted on Github

### ISSUE THREAD

**Issue by jeremylynch** [jossmac/react-images#339]
How can i use the uptodate version of react-images as hosted on Github? 

eg. `npm i jossmac/react-images` doesn't work as the `/dist` folder is not git tracked. Can we change this behaviour? 

Just need to remove `dist` from .gitignore

**Comment by jlaramie** [comment]
@jeremylynch  I just forked the repo yesterday to fix a bug in master. Feel free to use my built version by calling `npp i https://github.com/jlaramie/react-images.git#built`

**Comment by davwheat** [comment]
New updates are being released now!
