### ISSUE TITLE
How I can show both images and video in Carousel?

### ISSUE THREAD

**Issue by jjdechavez** [jossmac/react-images#343]
Is it possible to display in one Carousel component of videos and images.

I already tried which I'm getting issue in it. Thank you

**Comment by ashandrenko** [comment]
I made my own view component that would either render a video or an image.

**Comment by jjdechavez** [comment]
Can you give me an idea how you do it?

**Comment by jjdechavez** [comment]
> I made my own view component that would either render a video or an image.

Can share what process do you do? To achieve the goal? Thank you

**Comment by ashandrenko** [comment]
Something along the lines of this: 

```
const CustomeView = props => {
  const { data } = props;

  return (
    <div className={styles.view}>
      {data.videoUrl ? (
        <video width="320" height="240" controls>
            <source src="movie.mp4" type="video/mp4">
            <source src="movie.ogg" type="video/ogg">
           Your browser does not support the video tag.
        </video>
      ) : (
        <img className={styles.img} src={data.src} />
      )}
    </div>
  );
};
```

**Comment by jjdechavez** [comment]
@ashandrenko Nice I'll try that

**Comment by linh626688** [comment]
very nice solution @ashandrenko
