### ISSUE TITLE
Warnings are shown on opened image

### ISSUE THREAD

**Issue by zdrsoft** [jossmac/react-images#348]
**Steps to reproduce the behavior:**
The component is used with "react": "^16.11.0"

I use the component from react-images
(import Lightbox from 'react-images';)

When some image from the gallery is opened in full size, in the console is shown the following **Warnings:**
Warning: The <Container /> component appears to be a function component that returns a class instance. Change Container to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `Container.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React. 
    in Container (created by Lightbox)
    in Lightbox (created by ImageGallery)
    in ImageGallery (created by ...

Warning: The <Header /> component appears to be a function component that returns a class instance. Change Header to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `Header.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React. 
    in Header (created by Lightbox)
    in Lightbox (created by ...

Warning: The <Footer /> component appears to be a function component that returns a class instance. Change Footer to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `Footer.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React. 
    in Footer (created by Lightbox)
    in Lightbox (created by ...

**Expected behavior:**
**Do not show warnings.**

**Actual behavior:**
The component works but warnings are shown in the console.

**Comment by davwheat** [comment]
Can you double check to see if you're on the latest beta version?

**Comment by zdrsoft** [comment]
I am able to reproduce it on v0.5.19.
The latest version is not tested.

**Comment by davwheat** [comment]
That is an insanely old version which we aren't going to give support for anymore.
