### ISSUE TITLE
height in the viewPageStyles aligns content at the top of the page

### ISSUE THREAD

**Issue by florianuphoff** [jossmac/react-images#360]
**Steps to reproduce the behavior:**
1. Install or update `react-images` to the newest release `1.1.2`
2. Create a simple example as shown here: https://codesandbox.io/s/charming-vaughan-wxx7p
3. Click on the image to open the modal

**Expected behavior:**
The content of the lightbox is centered vertically and horizontally per default behavior.

Here is an example with the version 1.1.0
-> https://codesandbox.io/s/pedantic-easley-stnh7

**Actual behavior:**
The content of the lightbox is centered horizonally but is placed at the top the page.
-> https://codesandbox.io/s/charming-vaughan-wxx7p

**Whats causing the issue?** In this commit https://github.com/jossmac/react-images/commit/c6027190c1d19347284c27fd089b9b0c9d914598 the height in the viewPagerStyles is set to `100vh`.

It seems that there has been a restructuring of the rendered output, but removing the height property enables the flex-box to align the content as it was before the changes.
The alignment in `positionerCSS` in https://github.com/jossmac/react-images/blob/master/src/components/Modal/styled.js has no effect if the child element (in this case the viewPager) is set to `100vh`.

I guess that there has been a valid reason to add the `100vh`. Can you explain it? 

I'm going to create a pull request to fix this issue. We are using this plugin in our project so we need a fix asap. Great work and thank you for this plugin! 👍

**Comment by davwheat** [comment]
I set that in an attempt to fix some issues surrounding the navigation buttons, but I think it all works without that `100vh`.

**Comment by florianuphoff** [comment]
Okay thanks for that fast reply. So i'm going to create a pr to remove the `100vh`. 
Is it okay to bump the version up to 1.1.3 in that pr? I guess you're using semantic versioning

**Comment by davwheat** [comment]
Yep, that's perfect!
