### ISSUE TITLE
Carousels outside of full-screen modals broken in v1.1.3

### ISSUE THREAD

**Issue by nfrasser** [jossmac/react-images#366]
**Steps to reproduce the behavior:**
1. Create a `<Carousel />` component outside of a Modal with some images

**Expected behavior:**
The Carousel is no wider than its container

**Actual behavior:**
The Carousel is much wider and overflows from its container

For example, here's what the docs page at http://jossmac.github.io/react-images/#/styles should look like
![image](https://user-images.githubusercontent.com/1693461/80286109-84b94580-86f7-11ea-8a1b-e68e636fd9b2.png)

Here's what it looked like when I ran the development server in the latest version
![image](https://user-images.githubusercontent.com/1693461/80286124-98fd4280-86f7-11ea-92f7-e7d0b69fd590.png)

**Comment by nfrasser** [comment]
Looks like this issue was introduced in commit c6027190c1d19347284c27fd089b9b0c9d914598

Specifically, `width: 100vh,` should be removed from `viewPagerStyles` to fix the issue:
https://github.com/jossmac/react-images/blob/6855af0d4f5b5303d5e643316537d70a8124ed0e/src/components/Carousel.js#L9-L13

**Comment by aperkaz** [comment]
@nfrasser any news if this will be fixed?

**Comment by nfrasser** [comment]
@aperkaz I'm not sure, maybe @davwheat knows?

**Comment by davwheat** [comment]
Well I removed the section that someone said was causing the issue.

**Comment by nfrasser** [comment]
Can confirm it's fixed in v1.1.7, thanks @davwheat!
