### ISSUE TITLE
Ref owner warning about multiple React modules

### ISSUE THREAD

**Issue by Flyr1Q** [jossmac/react-images#43]
Working on a project with react & react 15.0.1 versions. React-images was not working and there is only warning from invariant.js about multiple React modules. 

I've deleted react from peer dependency and upgraded versions and now react-images is working.
Also, I've tried as a workaround to delete /node_modules/react-images/node_modules/react and react-dom, which lead to the same result, react-images started to work.

Not sure whether i'm doing something wrong. (npm - 3.8.7, node - 5.9.0)
Nevertheless, thank u for this lightbox, it is awesome.

**Comment by kachkaev** [comment]
Same issue here with React 15.0.2 – thanks for the workaround @Flyr1Q!

The lightbox started working after I manually deleted  `/node_modules/react-images/node_modules/react` & `/node_modules/react-images/node_modules/react-dom`. Should be fine while I'm playing with the project alone, but obviously this is something worth fixing.

**Comment by jossmac** [comment]
Might be time for an update. I'll try and fit it in this week.

Thank you both for creating/commenting issues, I really appreciate it. Otherwise this stuff flies under the radar for too long.

**Comment by jossmac** [comment]
@Flyr1Q @kachkaev @laurentvw @jjordy @becarlos

I've release v0.4.1 with updated dependencies.

Could you please get latest and let me know if this resolves your issues?

**Comment by Flyr1Q** [comment]
@jossmac I've just tried it, the warning still appears and gallery does not open. May be I have to reinstall node_modules or clean cache? Will wait for @kachkaev response :)

**Comment by kachkaev** [comment]
@Flyr1Q I did not experiment a lot, just ran the following and re-launched the app:
```bash
npm remove --save react-images
npm install --save react-images
```
No errors showed up in the console when I clicked on a couple of images. Which ones do you see?

**Comment by jjordy** [comment]
Im out of town for the weekend but I will upgrade when I get back and let you know the results. @jossmac Yo da man!

**Comment by Laurentvw** [comment]
I did what @kachkaev said and I'm still getting an error.

Here's the log after the install:

```
└─┬ react-images@0.4.1
  ├── jss@3.11.1
  ├── jss-camel-case@1.1.0
  ├── jss-nested@1.0.3
  ├── jss-px@1.0.0
  ├─┬ jss-vendor-prefixer@2.0.0
  │ └── css-vendor@0.3.3
  ├── UNMET PEER DEPENDENCY react@15.0.2
  ├── react-addons-transition-group@15.0.2
  ├── react-dom@15.0.2
  ├── react-jss@2.0.6
  └── react-swipeable@3.4.0
```

My package.json has `"react": "^15.0.0"`.

The error in question when clicking an image: 
`invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

I think the react dependency of react-images needs to be less strict:
```
"react": "^15.0.2",
"react-addons-transition-group": "^15.0.2",
"react-dom": "^15.0.2",
```
Maybe instead of `^15.0.2` it should be set to `>=0.14`?

**Comment by jossmac** [comment]
After some tinkering over the weekend `0.4.3` should cover everyone's needs. Thank you all for being patient.

Please try again and let me know how you go :)

**Comment by Flyr1Q** [comment]
@jossmac Yeah, everything is working now. Thanks @JedWatson @jossmac
