### ISSUE TITLE
'X of Y' template in props

### ISSUE THREAD

**Issue by kachkaev** [jossmac/react-images#44]
Hi Joss,

Just wondering if you can implement a little improvement when you change anything in the library next time. It is about making `X of Y` something you can pass as a prop. This will be extremely useful in multilingual interfaces.

Here is how a feature can look like:

```jsx
<Lightbox
    images={[{ src: 'http://example.com/img1.jpg' }, { src: 'http://example.com/img2.jpg' }]}
    imageCountTemplate="{current} из {total}" // ← Russian
/>
```
 Certainly, `imageCountTemplate` can be undefined, which will output `{current} of {total}` as this is happening now.

Cheers!

**Comment by jossmac** [comment]
Hi @kachkaev,

That sounds good. For ease of use/implementation how about `imageCountSeparator`?

It would default to "of", you could of course replace with "из" or anything else.

**Comment by kachkaev** [comment]
This would work for me. I just suggested a template not a separator to
potentially cover a wider set of cases. Maybe this is redundant indeed.

Alex

**Comment by kachkaev** [comment]
Thanks for implementing this feature @jossmac! Looks like the lib directory has still got the old content. Could you please update it as well?

**Comment by jossmac** [comment]
@kachkaev sorry mate!

New build on NPM

**Comment by kachkaev** [comment]
Works great, thank you!

**Comment by MilosJo** [comment]
This isn't working with new `**1.x**`. And it is pretty neat feature.

**Comment by jossmac** [comment]
@MilosJo in `1.x` you can just replace the `FooterCount` component with whatever you like.
