### ISSUE TITLE
Just updated fro 0.3.2 to 0.4.5 - transitivie peer dependency on react 15.0.2

### ISSUE THREAD

**Issue by rluiten** [jossmac/react-images#47]
I am now getting the following npm warning.

npm ERR! peer dep missing: react@^15.0.2, required by react-addons-transition-group@15.0.2

The react-addons-transition-group module had peer dependency on "react": "^15.0.2"

You module indicates peer dependencies of react ^0.14 or 15.0^ yet it pulls in that module.

Is this going to cause a problem for me at run time in 0.14.8, as I can't update it yet ? 
Is there maybe someway I can address the complaint it so i don't get the warning ?

It basically appears to work ok at moment.

Thanks for the useful module.
Robin

**Comment by jossmac** [comment]
@rluiten We've made [quite a few changes](/jossmac/react-images/blob/master/HISTORY.md) since this was opened, would you mind installing latest and letting me know if your problem persists?

**Comment by rluiten** [comment]
I've updated to 15 and up to latest now as well as I was waiting on a few specific other packages to support 15.x at the time.
I did not have a problem even when I got the warning with the behaviour of react-images.
I should have come back and closed this sorry.
