### ISSUE TITLE
I just tried out 0.4.6 and got the follow message in console log.

### ISSUE THREAD

**Issue by rluiten** [jossmac/react-images#48]
main.bundle.js:3396 Warning: FirstChild(...): No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

I had a quick look it almost seems to me that FirstChild if its a component is missing render().

**Comment by rluiten** [comment]
Oh maybe the failure here is because I am in react 0.14.8 and Portal.js is using 'react-addons-transition-group' which has a peer depdency on react ^15.0.1.

**Comment by jossmac** [comment]
Ref #47

**Comment by kyle-ruan** [comment]
Have you solved this? I'm getting same issue.

**Comment by rluiten** [comment]
I ended up updating to React 15, turned out 3 other libraries I was waiting on had updated so I was able to update to it.

**Comment by jossmac** [comment]
See #47
