### ISSUE TITLE
Upgrading to 0.3.3 error

### ISSUE THREAD

**Issue by neptunian** [jossmac/react-images#52]
From the console when clicking on the "preview" image to open the lightbox this error appears:

invariant.js:39 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

The page seems to hang then I try clicking again and get this error:

ReactTransitionGroup.js:132 Uncaught TypeError: Cannot read property 'componentWillEnter' of undefined

see: https://github.com/neptunian/react-photo-gallery/issues/5

**Comment by neptunian** [comment]
The version of React and React DOM I'm using is 0.14.8.  The user claims updating react-images to 0.4.x and updating react & react-dom to 15.x fixes it, so there seems to be compatibility issues.

**Comment by jossmac** [comment]
@neptunian is this still an issue?

**Comment by neptunian** [comment]
@jossmac  I ended up updating everything but probably.  Might want to be careful using the ^ in package.json and letting things auto update to minor versions?  I've started using ~

**Comment by jossmac** [comment]
@neptunian might be time to up the `major` so we can properly follow `semver`?
