### ISSUE TITLE
When displaying Lightbox, warning about SVG's SMIL animations deprecated

### ISSUE THREAD

**Issue by neptunian** [jossmac/react-images#55]
Click on lightbox thumbnail in the example.  Read message in the console:

"SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead."

https://github.com/neptunian/react-photo-gallery/issues/10

**Comment by jossmac** [comment]
This could be resolved by using something like http://elemental-ui.com/spinner

@neptunian what do you think?

**Comment by neptunian** [comment]
@jossmac  Sure any kind of css animation would work.  Is the loading animation the only SVG animation that needs replacing?

**Comment by jossmac** [comment]
The spinner is the only animating SVG. We could also just take it out - I'm not sure if anyone wants it?

**Comment by neptunian** [comment]
@jossmac I think it's a nice to have for those slower connections if its not causing any issues.  Once preloading is implemented it my not b as necessary.  Perhaps it can be optional.

**Comment by neptunian** [comment]
resolved in commit ed005d877767ddb5821cb010447693eda5bfbb26
