### ISSUE TITLE
Feature: download image (open full size image in new window)

### ISSUE THREAD

**Issue by RobinTail** [jossmac/react-images#58]
> please ensure the change is aligned with the project roadmap by opening an issue first

Hello. I'd like to implement a new feature which will provide an ability to download currently viewed image by opening it in a new browser window. This can be also useful when viewing "thin" images. I plan to add the property .showDownloadButton and display a nice icon in the CloseBar. Here is a screenshot.

Are you interested of this feature implementation?

![2016-06-23_03-18-12](https://cloud.githubusercontent.com/assets/13189514/16288102/43e3862c-38f1-11e6-8df0-47cc2f52d079.png)

**Comment by jossmac** [comment]
@RobinTail Good idea, that could be useful.

Perhaps we could make it more generic though, like an array of elements to render in the top bar. That way consumers can add whatever functionality and style they want.

Thoughts?

**Comment by jossmac** [comment]
Also, thank you for raising an issue first!

**Comment by RobinTail** [comment]
Nice idea, @jossmac  ^_^
Then I can add a new prop to `Lightbox` like this: 
`customControls: PropTypes.arrayOf(PropTypes.node),`

There also will be some changes to `renderCloseButton()` method and minor style fix to `.closeButton` class.

Do you agree?

**Comment by jossmac** [comment]
Sounds good to me. Looking forward to your PR

**Comment by neptunian** [comment]
I think placement at the bottom left would be more appropriate.. perhaps just before the photo count.  Similar the way most "lightboxes" are arranged like Flickr and Facebook.

**Comment by RobinTail** [comment]
@jossmac PR: #60

**Comment by RobinTail** [comment]
@jossmac, after releasing version 0.4.7, i do not see my new feature in build file https://github.com/jossmac/react-images/blob/master/lib/Lightbox.js . There is no new prop `.customControls`

**Comment by jossmac** [comment]
@RobinTail this is sorted now, right?

**Comment by RobinTail** [comment]
@jossmac Yes, thank you for updating build files :)
