### ISSUE TITLE
FirstChild(...): No `render` method found on the returned component instance

### ISSUE THREAD

**Issue by PeteLuo** [jossmac/react-images#59]
FirstChild(...): No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

I gave it a try, Issue is in the \react-images\lib\Fade.js 33 line to return empty.Want to be able to repair

**Comment by ArturAmbartsumov** [comment]
i have the same problem too

**Comment by PeteLuo** [comment]
@ArturAmbartsumov in \node_modules\react-images\lib\Fade.js 33 line
Replace return kids[0] || null;
with
return kids[0] || _react.createElement('div',null);
please take a chance.

**Comment by Genert** [comment]
There is still problem with rendering on this component.

Error message: "Uncaught TypeError: inst.render is not a function".

Compiled code - Portal.js lines 57 and 52.

**Comment by PeteLuo** [comment]
react v15.0.2 is no problem

**Comment by Genert** [comment]
Yes indeed, this problem occurs with older React versions.

Solution: use latest React.

**Comment by iinc** [comment]
Upgrading react to the latest version fixes this problem. Thanks guys

**Comment by jossmac** [comment]
Fixed by 591761f
