### ISSUE TITLE
Repo Management

### ISSUE THREAD

**Issue by jossmac** [jossmac/react-images#62]
Hello everyone!

I'm afraid that I've become too busy at work to give this package the time it needs. If anyone would like to come on board as a collaborator, either just to help out, or possibly to take the reigns, I'd really appreciate it.

Pinging you guys specifically because of your issue/PR support:
@neptunian, @pradel, @newsiberian, @RobinTail

**Comment by neptunian** [comment]
I'd be happy to!

**Comment by jossmac** [comment]
@neptunian great! Added 😄

**Comment by neptunian** [comment]
@jossmac  awesome thanks!

**Comment by neptunian** [comment]
@jossmac  i am also a bit swamped right now but plan to give this attention soon!

**Comment by jossmac** [comment]
Thanks for getting on board @neptunian 🎉
