### ISSUE TITLE
Add a property callback function for photo currentImage state change

### ISSUE THREAD

**Issue by neptunian** [jossmac/react-images#7]
Like onClose property, would there be an interest in an optional onChangeImage property or something like that?  

Here is the scenario that I've run into:
My responsive Gallery component must re render itself when the browser window width changes.  This turns out to be an issue when using a phone and changing orientation.  The Lightbox gets rendered again and the image gets reset to the 'initialImage' index which is whatever it opened the Lightbox with initially.  If i had this callback I could keep track of Lightbox's current image state and keep my 'initialImage' up to date.

**Comment by jossmac** [comment]
@neptunian you've made a good point. This problem is a symptom of having made the component maintain it's own state.

I'll update the component to be stateless
