### ISSUE TITLE
add thumbnail preview

### ISSUE THREAD

**Issue by GregoryPotdevin** [jossmac/react-images#72]
Are there any plans to add a bottom bar with thumbnail preview/selection (like [react-image-gallery](http://linxtion.com/demo/react-image-gallery/)) ?

![image](https://cloud.githubusercontent.com/assets/1522455/17691828/108c132c-6397-11e6-86a5-650e1cee4cfa.png)

It could be nice to be able to plug an external component at the bottom of the Lightbox to add a custom one if needed.

**Comment by jossmac** [comment]
Absolutely. This needs some planning, but is something that's been on my mind for a while

**Comment by neptunian** [comment]
Flickr also implements this in context of a lightbox instead of gallery :
https://www.flickr.com/photos/neptunian/28167115654/in/photostream/

**Comment by jossmac** [comment]
Oh that's a nice implementation, I like the subtle drop shadow when the thumbnails are enlarged. Also, great shot 😉

**Comment by GregoryPotdevin** [comment]
Quick and basic test : http://tamago.fr/react-images/

![image](https://cloud.githubusercontent.com/assets/1522455/17767263/9576c41c-652f-11e6-9ffb-f97d772a6db3.png)

Scrolls (not automatically yet) when there are too many thumbnails, uses "thumbnail" instead of "src" if given. Added onClickThumbnail (like onClickPrev/Next).

Could be easily changed to a "paginated" version like Flickr.

**Comment by jossmac** [comment]
Dude, that's awesome! Looking forward to the PR

**Comment by GregoryPotdevin** [comment]
Just updated the version to also a second Thumbnails components : `PaginatedThumbnails`

![image](https://cloud.githubusercontent.com/assets/1522455/17774544/75edc904-6554-11e6-93df-e032a8739a6b.png)

In my current fork the thumbnails component can be passed to Lightbox, so you can write stuff like 
```jsx 
<Lightbox 
    images={...}
    thumbnails={PaginatedThumbnails} />
```

If you need to pass some props to the thumbnail component, you can do it like this (not very intuitive)
```jsx 
<Lightbox 
    images={...}
    thumbnails={(props) => <PaginatedThumbnails {...props} offset={5} />} />
```

The code for this one is more complicated as it has some internal state to manage the "current page". 

I guess I can do a PR, but it probably needs some discussion to see what API suits you best.

**Comment by GregoryPotdevin** [comment]
@jossmac do you have a gitter for this project ? I'll be doing some open source image components for my company and wanted to see if it's something that could be added to react-images or should be a separate project.

**Comment by jossmac** [comment]
Just created https://gitter.im/react-images

Yeah that'd be great. Just let me know what you're building and hopefully it can find its way back into this repo for the community 😄

**Comment by infacq** [comment]
+1
