### ISSUE TITLE
left and right arrow doesn't work after upgrading from 0.4.10 to 0.4.11

### ISSUE THREAD

**Issue by elisei-timofte** [jossmac/react-images#74]
After I load in my app react-images, in all inputs, left and right arrow don't working anymore anywhere in the app. (Right arrow works only after 4-5 strikes.)

**Comment by jossmac** [comment]
Interesting; could you tell please set `preloadNextImage` to `false` on your `<Lightbox />` and let me know if it fixes the behaviour?

Also, please let me know your:
- OS
- browser
- react version

Thanks!

**Comment by elisei-timofte** [comment]
Hi,

So my specs are:
 - OSX El Capitan 10.11.6
 - Browser: Google Chorme 52.0.2743.116 (64-bit)
 - React: 15.3.0

The fix doesn't work. Is there anything else I can try?

Thanks!

**Comment by jossmac** [comment]
Wow, we're running the exact same specs; perhaps something's up in the function you're passing to `onClickPrev`/`onClickNext`?

**Comment by elisei-timofte** [comment]
This is how I use the LightBox

```
<Lightbox
        images              = {@props.commentAttachments.map((a) -> {src: a.link()})}
        isOpen              = {@state.lightboxIndex >= 0}
        currentImage        = {@state.lightboxIndex}
        onClickPrev         = {=> @setState(lightboxIndex: @state.lightboxIndex-1) unless @unmounted}
        onClickNext         = {=> @setState(lightboxIndex: @state.lightboxIndex+1) unless @unmounted}
        onClose             = {=> @setState(lightboxIndex: -1) unless @unmounted}
        backdropClosesModal = {true}
        showCloseButton     = {false}
      />

componentWillUnmount: ->
    @unmounted = true
```

Thanks!

**Comment by jossmac** [comment]
@elisei-timofte I'm afraid I can't reproduce this behaviour.

**Comment by elisei-timofte** [comment]
I'll try to reproduce this in a repo.

**Comment by pjarmalavicius** [comment]
This problem is because event listeners are not removed in componentWillUnmount.
window.removeEventListener('keydown', this.handleKeyboardInput); this should be called in componentWillUnmount

**Comment by GregoryPotdevin** [comment]
I think this has been fixed a while ago when the event binding code was updated.

**Comment by FDiskas** [comment]
Please make an new release for npm to.
