### ISSUE TITLE
Event Listener for KeyboardInput doesn't destroy on Unmount

### ISSUE THREAD

**Issue by L3V147H4N** [jossmac/react-images#76]
After the Lightbox Component is unmounted the Listener for Keyboard remains active

**Comment by GregoryPotdevin** [comment]
A quick fix would be to just remove it on unmount.

Something I feel could be cleaner is how some react keyboard handlers work : using a dedicated component. 

In `renderDialog`, add something like 
```jsx
{enableKeyboardInput && <KeyDownHandler callback={this.handleKeyboardInput} />}
```

and then KeyHandler would be the one doing `addEventListener`/`removeEventListener` in it's mount/unmount. This avoids having to manage the removeEventListener in both `componentWillReceiveProps` and `componentWillUnmount`.

**Comment by aknuds1** [comment]
Yeah, I just noticed this issue :/ 👍

**Comment by GregoryPotdevin** [comment]
Actually there's the same issue with the body scroll lock.
```jsx
		// handle body scroll
		if (nextProps.isOpen) {
			bodyScroll.blockScroll();
		} else {
			bodyScroll.allowScroll();
		}
```

This is in `componentWillReceiveProps`, so doesn't trigger if the Lightbox component is added and directly opened, or directly removed without hiding it first. This can happen when using a router, for example.

**Comment by GregoryPotdevin** [comment]
Something like this works quite well : https://github.com/appcraft/appcraft-forms/blob/master/src/components/ScrollLock.js
