### ISSUE TITLE
bodyScroll

### ISSUE THREAD

**Issue by tannerjt** [jossmac/react-images#89]
It would appear you've removed the bodyScroll module 'src/utils/bodyScroll.js', which is causing trouble trying to build with gulp.  Is this no longer needed?

**Comment by GregoryPotdevin** [comment]
It was remove in favor of a component-based body scroll lock, so that file isn't used anymore

**Comment by tannerjt** [comment]
That makes sense.  I ended up removing it for a custom gulp build.  Thanks for this library, looking really great!
