### ISSUE TITLE
Support Fullscreen

### ISSUE THREAD

**Issue by jossmac** [jossmac/react-images#90]
Via a new property `allowFullscreen` use the [HTML5 Fullscreen API](https://davidwalsh.name/fullscreen) with an icon besides the close button.

**Comment by aliogaili** [comment]
Was this implemented? I think it's a crucial for this component full screen for mobile view.

**Comment by freelyageha** [comment]
I'm really looking forward to this feature.

**Comment by jossmac** [comment]
Resolved in v1 #199
