### ISSUE TITLE
Consolidate options

### ISSUE THREAD

**Issue by jossmac** [jossmac/react-images#91]
Consider merging aesthetic properties into a single `options` object, something like:

``` JSX
<Lightbox
  images={[...]}
  options={{
    allowFullscreen: true,
    backdropClosesModal: false,
    enableKeyboardInput: true,
    imageCountSeparator: ' / ',
    preloadNextImage: true,
    showCloseButton: true,
    showImageCount: true,
    showThumbnails: false,
  }}
/>
```

@neptunian @GregoryPotdevin what are your thoughts on this?

**Comment by GregoryPotdevin** [comment]
Not sure.

Pros : would clean up the "top level" props, so it's easier to see that images are important and the rest is secondary. I guess it could also help if you have a set of props to pass down to other components
Cons : could make it harder later on to make it a PureRenderer as you'd have to compare the options and not just the top level props, but that's a minor issue. And if the image array is computed using Array.map it'll bypass the PureRenderer as well.

I'd say "stick with what people are the most used to", so it might be worth checking out the other gallery/image components to see what they chose. Also, it's not purely aesthetic properties, at least for `backdropClosesModal`, `preloadNextImage`, and `enableKeyboardInput` (but they are secondary props compared to images and the callbacks).

**Comment by jossmac** [comment]
Yeah, that's basically what I was thinking.

Not really concerned with a shallow merge of the options, and like you say there's a couple of behavioural props but I think they fit in this context. From experience with other libraries I've found "options" to be common practice and it does tidy things up considerably.

In regard to "PureRenderer" (I think you're talking about a [stateless functional components](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions)?), I need `context` for theming and will need `state` to implement touch/swipe support.

Thank you for responding so quickly, that was very helpful to talk through :)

**Comment by jossmac** [comment]
No longer an issue with prop reduction in v1 #199
