### ISSUE TITLE
How to set  draggable=False in React-Images

### ISSUE THREAD

**Issue by chandrasekarb** [jossmac/react-images#92]
I tried https://github.com/jossmac/react-images …, It awesome,
I Need to disable the rightclick and draggable=false on images, How to prevent the image from drag and drop on images like < img src=".." draggable="false" >  Please Provide me some solution?

**Comment by chandrasekarb** [comment]
I tried https://github.com/jossmac/react-images …, It awesome,
I Need to disable the rightclick and draggable=false on images, How to prevent the image from drag and drop on images like < img src=".." draggable="false" >Any one  Please Provide me a solution?

**Comment by jossmac** [comment]
Please see #87 - we intend to implement an`imageRenderer` prop so you can pass whatever you want through. Just need some time to build it
